package com.kakasure.bqf.dao.model;

import java.util.Date;

public class Announcemulti {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunear_announcemulti.ANNOUNCEMULTI_ID
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    private String announcemultiId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunear_announcemulti.USER_ID
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunear_announcemulti.COPYRIGHT_USER_ID
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    private String copyrightUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunear_announcemulti.COPYRIGHTMULTI_ID
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    private String copyrightmultiId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunear_announcemulti.CODE_ID
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    private String codeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunear_announcemulti.SCAN_CODE_LINK
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    private String scanCodeLink;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunear_announcemulti.SCAN_CODE_NUM
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    private Integer scanCodeNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunear_announcemulti.IMG_LINK
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    private String imgLink;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunear_announcemulti.DATE_CREATE
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    private Date dateCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunear_announcemulti.DATE_MODIFY
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    private Date dateModify;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunear_announcemulti.IS_DELETE
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    private String isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunear_announcemulti.ANNOUNCEMULTI_ID
     *
     * @return the value of yunear_announcemulti.ANNOUNCEMULTI_ID
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    public String getAnnouncemultiId() {
        return announcemultiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunear_announcemulti.ANNOUNCEMULTI_ID
     *
     * @param announcemultiId the value for yunear_announcemulti.ANNOUNCEMULTI_ID
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    public void setAnnouncemultiId(String announcemultiId) {
        this.announcemultiId = announcemultiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunear_announcemulti.USER_ID
     *
     * @return the value of yunear_announcemulti.USER_ID
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunear_announcemulti.USER_ID
     *
     * @param userId the value for yunear_announcemulti.USER_ID
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunear_announcemulti.COPYRIGHT_USER_ID
     *
     * @return the value of yunear_announcemulti.COPYRIGHT_USER_ID
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    public String getCopyrightUserId() {
        return copyrightUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunear_announcemulti.COPYRIGHT_USER_ID
     *
     * @param copyrightUserId the value for yunear_announcemulti.COPYRIGHT_USER_ID
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    public void setCopyrightUserId(String copyrightUserId) {
        this.copyrightUserId = copyrightUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunear_announcemulti.COPYRIGHTMULTI_ID
     *
     * @return the value of yunear_announcemulti.COPYRIGHTMULTI_ID
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    public String getCopyrightmultiId() {
        return copyrightmultiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunear_announcemulti.COPYRIGHTMULTI_ID
     *
     * @param copyrightmultiId the value for yunear_announcemulti.COPYRIGHTMULTI_ID
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    public void setCopyrightmultiId(String copyrightmultiId) {
        this.copyrightmultiId = copyrightmultiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunear_announcemulti.CODE_ID
     *
     * @return the value of yunear_announcemulti.CODE_ID
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    public String getCodeId() {
        return codeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunear_announcemulti.CODE_ID
     *
     * @param codeId the value for yunear_announcemulti.CODE_ID
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    public void setCodeId(String codeId) {
        this.codeId = codeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunear_announcemulti.SCAN_CODE_LINK
     *
     * @return the value of yunear_announcemulti.SCAN_CODE_LINK
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    public String getScanCodeLink() {
        return scanCodeLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunear_announcemulti.SCAN_CODE_LINK
     *
     * @param scanCodeLink the value for yunear_announcemulti.SCAN_CODE_LINK
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    public void setScanCodeLink(String scanCodeLink) {
        this.scanCodeLink = scanCodeLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunear_announcemulti.SCAN_CODE_NUM
     *
     * @return the value of yunear_announcemulti.SCAN_CODE_NUM
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    public Integer getScanCodeNum() {
        return scanCodeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunear_announcemulti.SCAN_CODE_NUM
     *
     * @param scanCodeNum the value for yunear_announcemulti.SCAN_CODE_NUM
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    public void setScanCodeNum(Integer scanCodeNum) {
        this.scanCodeNum = scanCodeNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunear_announcemulti.IMG_LINK
     *
     * @return the value of yunear_announcemulti.IMG_LINK
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    public String getImgLink() {
        return imgLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunear_announcemulti.IMG_LINK
     *
     * @param imgLink the value for yunear_announcemulti.IMG_LINK
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    public void setImgLink(String imgLink) {
        this.imgLink = imgLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunear_announcemulti.DATE_CREATE
     *
     * @return the value of yunear_announcemulti.DATE_CREATE
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    public Date getDateCreate() {
        return dateCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunear_announcemulti.DATE_CREATE
     *
     * @param dateCreate the value for yunear_announcemulti.DATE_CREATE
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    public void setDateCreate(Date dateCreate) {
        this.dateCreate = dateCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunear_announcemulti.DATE_MODIFY
     *
     * @return the value of yunear_announcemulti.DATE_MODIFY
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    public Date getDateModify() {
        return dateModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunear_announcemulti.DATE_MODIFY
     *
     * @param dateModify the value for yunear_announcemulti.DATE_MODIFY
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    public void setDateModify(Date dateModify) {
        this.dateModify = dateModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunear_announcemulti.IS_DELETE
     *
     * @return the value of yunear_announcemulti.IS_DELETE
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    public String getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunear_announcemulti.IS_DELETE
     *
     * @param isDelete the value for yunear_announcemulti.IS_DELETE
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    public void setIsDelete(String isDelete) {
        this.isDelete = isDelete;
    }
}