package com.kakasure.bqf.dao.model;

import java.util.Date;

public class Codenum {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunear_codenum.CODENUM_ID
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    private String codenumId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunear_codenum.COPYRIGHTMULTI_ID
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    private String copyrightmultiId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunear_codenum.BQF_USER_ID
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    private String bqfUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunear_codenum.FBF_USER_ID
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    private String fbfUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunear_codenum.USER_ID
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunear_codenum.IP
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    private String ip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunear_codenum.DATE_CREATE
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    private Date dateCreate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunear_codenum.CODENUM_ID
     *
     * @return the value of yunear_codenum.CODENUM_ID
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    public String getCodenumId() {
        return codenumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunear_codenum.CODENUM_ID
     *
     * @param codenumId the value for yunear_codenum.CODENUM_ID
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    public void setCodenumId(String codenumId) {
        this.codenumId = codenumId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunear_codenum.COPYRIGHTMULTI_ID
     *
     * @return the value of yunear_codenum.COPYRIGHTMULTI_ID
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    public String getCopyrightmultiId() {
        return copyrightmultiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunear_codenum.COPYRIGHTMULTI_ID
     *
     * @param copyrightmultiId the value for yunear_codenum.COPYRIGHTMULTI_ID
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    public void setCopyrightmultiId(String copyrightmultiId) {
        this.copyrightmultiId = copyrightmultiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunear_codenum.BQF_USER_ID
     *
     * @return the value of yunear_codenum.BQF_USER_ID
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    public String getBqfUserId() {
        return bqfUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunear_codenum.BQF_USER_ID
     *
     * @param bqfUserId the value for yunear_codenum.BQF_USER_ID
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    public void setBqfUserId(String bqfUserId) {
        this.bqfUserId = bqfUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunear_codenum.FBF_USER_ID
     *
     * @return the value of yunear_codenum.FBF_USER_ID
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    public String getFbfUserId() {
        return fbfUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunear_codenum.FBF_USER_ID
     *
     * @param fbfUserId the value for yunear_codenum.FBF_USER_ID
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    public void setFbfUserId(String fbfUserId) {
        this.fbfUserId = fbfUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunear_codenum.USER_ID
     *
     * @return the value of yunear_codenum.USER_ID
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunear_codenum.USER_ID
     *
     * @param userId the value for yunear_codenum.USER_ID
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunear_codenum.IP
     *
     * @return the value of yunear_codenum.IP
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    public String getIp() {
        return ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunear_codenum.IP
     *
     * @param ip the value for yunear_codenum.IP
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    public void setIp(String ip) {
        this.ip = ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunear_codenum.DATE_CREATE
     *
     * @return the value of yunear_codenum.DATE_CREATE
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    public Date getDateCreate() {
        return dateCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunear_codenum.DATE_CREATE
     *
     * @param dateCreate the value for yunear_codenum.DATE_CREATE
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    public void setDateCreate(Date dateCreate) {
        this.dateCreate = dateCreate;
    }
}