package com.kakasure.bqf.dao.model;

import java.util.Date;

public class Draw {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunear_draw.DRAW_ID
     *
     * @mbggenerated Wed Sep 28 11:17:07 CST 2016
     */
    private String drawId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunear_draw.USER_ID
     *
     * @mbggenerated Wed Sep 28 11:17:07 CST 2016
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunear_draw.DRAW_TYPE
     *
     * @mbggenerated Wed Sep 28 11:17:07 CST 2016
     */
    private String drawType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunear_draw.DRAW_NUMBER
     *
     * @mbggenerated Wed Sep 28 11:17:07 CST 2016
     */
    private String drawNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunear_draw.DRAW_HOLDER
     *
     * @mbggenerated Wed Sep 28 11:17:07 CST 2016
     */
    private String drawHolder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunear_draw.DRAW_BANK
     *
     * @mbggenerated Wed Sep 28 11:17:07 CST 2016
     */
    private String drawBank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunear_draw.AMOUNT
     *
     * @mbggenerated Wed Sep 28 11:17:07 CST 2016
     */
    private Double amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunear_draw.IS_SHANGHAI
     *
     * @mbggenerated Wed Sep 28 11:17:07 CST 2016
     */
    private String isShanghai;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunear_draw.IS_TRAFFIC_BANK
     *
     * @mbggenerated Wed Sep 28 11:17:07 CST 2016
     */
    private String isTrafficBank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunear_draw.IS_COMPANY
     *
     * @mbggenerated Wed Sep 28 11:17:07 CST 2016
     */
    private String isCompany;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunear_draw.POUNDAGE
     *
     * @mbggenerated Wed Sep 28 11:17:07 CST 2016
     */
    private Double poundage;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunear_draw.REMARKS
     *
     * @mbggenerated Wed Sep 28 11:17:07 CST 2016
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunear_draw.RSLT_MSG
     *
     * @mbggenerated Wed Sep 28 11:17:07 CST 2016
     */
    private String rsltMsg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunear_draw.STATUS
     *
     * @mbggenerated Wed Sep 28 11:17:07 CST 2016
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunear_draw.DATE_CREATE
     *
     * @mbggenerated Wed Sep 28 11:17:07 CST 2016
     */
    private Date dateCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunear_draw.DATE_STATUS
     *
     * @mbggenerated Wed Sep 28 11:17:07 CST 2016
     */
    private Date dateStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunear_draw.DRAW_ID
     *
     * @return the value of yunear_draw.DRAW_ID
     *
     * @mbggenerated Wed Sep 28 11:17:07 CST 2016
     */
    public String getDrawId() {
        return drawId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunear_draw.DRAW_ID
     *
     * @param drawId the value for yunear_draw.DRAW_ID
     *
     * @mbggenerated Wed Sep 28 11:17:07 CST 2016
     */
    public void setDrawId(String drawId) {
        this.drawId = drawId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunear_draw.USER_ID
     *
     * @return the value of yunear_draw.USER_ID
     *
     * @mbggenerated Wed Sep 28 11:17:07 CST 2016
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunear_draw.USER_ID
     *
     * @param userId the value for yunear_draw.USER_ID
     *
     * @mbggenerated Wed Sep 28 11:17:07 CST 2016
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunear_draw.DRAW_TYPE
     *
     * @return the value of yunear_draw.DRAW_TYPE
     *
     * @mbggenerated Wed Sep 28 11:17:07 CST 2016
     */
    public String getDrawType() {
        return drawType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunear_draw.DRAW_TYPE
     *
     * @param drawType the value for yunear_draw.DRAW_TYPE
     *
     * @mbggenerated Wed Sep 28 11:17:07 CST 2016
     */
    public void setDrawType(String drawType) {
        this.drawType = drawType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunear_draw.DRAW_NUMBER
     *
     * @return the value of yunear_draw.DRAW_NUMBER
     *
     * @mbggenerated Wed Sep 28 11:17:07 CST 2016
     */
    public String getDrawNumber() {
        return drawNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunear_draw.DRAW_NUMBER
     *
     * @param drawNumber the value for yunear_draw.DRAW_NUMBER
     *
     * @mbggenerated Wed Sep 28 11:17:07 CST 2016
     */
    public void setDrawNumber(String drawNumber) {
        this.drawNumber = drawNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunear_draw.DRAW_HOLDER
     *
     * @return the value of yunear_draw.DRAW_HOLDER
     *
     * @mbggenerated Wed Sep 28 11:17:07 CST 2016
     */
    public String getDrawHolder() {
        return drawHolder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunear_draw.DRAW_HOLDER
     *
     * @param drawHolder the value for yunear_draw.DRAW_HOLDER
     *
     * @mbggenerated Wed Sep 28 11:17:07 CST 2016
     */
    public void setDrawHolder(String drawHolder) {
        this.drawHolder = drawHolder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunear_draw.DRAW_BANK
     *
     * @return the value of yunear_draw.DRAW_BANK
     *
     * @mbggenerated Wed Sep 28 11:17:07 CST 2016
     */
    public String getDrawBank() {
        return drawBank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunear_draw.DRAW_BANK
     *
     * @param drawBank the value for yunear_draw.DRAW_BANK
     *
     * @mbggenerated Wed Sep 28 11:17:07 CST 2016
     */
    public void setDrawBank(String drawBank) {
        this.drawBank = drawBank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunear_draw.AMOUNT
     *
     * @return the value of yunear_draw.AMOUNT
     *
     * @mbggenerated Wed Sep 28 11:17:07 CST 2016
     */
    public Double getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunear_draw.AMOUNT
     *
     * @param amount the value for yunear_draw.AMOUNT
     *
     * @mbggenerated Wed Sep 28 11:17:07 CST 2016
     */
    public void setAmount(Double amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunear_draw.IS_SHANGHAI
     *
     * @return the value of yunear_draw.IS_SHANGHAI
     *
     * @mbggenerated Wed Sep 28 11:17:07 CST 2016
     */
    public String getIsShanghai() {
        return isShanghai;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunear_draw.IS_SHANGHAI
     *
     * @param isShanghai the value for yunear_draw.IS_SHANGHAI
     *
     * @mbggenerated Wed Sep 28 11:17:07 CST 2016
     */
    public void setIsShanghai(String isShanghai) {
        this.isShanghai = isShanghai;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunear_draw.IS_TRAFFIC_BANK
     *
     * @return the value of yunear_draw.IS_TRAFFIC_BANK
     *
     * @mbggenerated Wed Sep 28 11:17:07 CST 2016
     */
    public String getIsTrafficBank() {
        return isTrafficBank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunear_draw.IS_TRAFFIC_BANK
     *
     * @param isTrafficBank the value for yunear_draw.IS_TRAFFIC_BANK
     *
     * @mbggenerated Wed Sep 28 11:17:07 CST 2016
     */
    public void setIsTrafficBank(String isTrafficBank) {
        this.isTrafficBank = isTrafficBank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunear_draw.IS_COMPANY
     *
     * @return the value of yunear_draw.IS_COMPANY
     *
     * @mbggenerated Wed Sep 28 11:17:07 CST 2016
     */
    public String getIsCompany() {
        return isCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunear_draw.IS_COMPANY
     *
     * @param isCompany the value for yunear_draw.IS_COMPANY
     *
     * @mbggenerated Wed Sep 28 11:17:07 CST 2016
     */
    public void setIsCompany(String isCompany) {
        this.isCompany = isCompany;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunear_draw.POUNDAGE
     *
     * @return the value of yunear_draw.POUNDAGE
     *
     * @mbggenerated Wed Sep 28 11:17:07 CST 2016
     */
    public Double getPoundage() {
        return poundage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunear_draw.POUNDAGE
     *
     * @param poundage the value for yunear_draw.POUNDAGE
     *
     * @mbggenerated Wed Sep 28 11:17:07 CST 2016
     */
    public void setPoundage(Double poundage) {
        this.poundage = poundage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunear_draw.REMARKS
     *
     * @return the value of yunear_draw.REMARKS
     *
     * @mbggenerated Wed Sep 28 11:17:07 CST 2016
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunear_draw.REMARKS
     *
     * @param remarks the value for yunear_draw.REMARKS
     *
     * @mbggenerated Wed Sep 28 11:17:07 CST 2016
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunear_draw.RSLT_MSG
     *
     * @return the value of yunear_draw.RSLT_MSG
     *
     * @mbggenerated Wed Sep 28 11:17:07 CST 2016
     */
    public String getRsltMsg() {
        return rsltMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunear_draw.RSLT_MSG
     *
     * @param rsltMsg the value for yunear_draw.RSLT_MSG
     *
     * @mbggenerated Wed Sep 28 11:17:07 CST 2016
     */
    public void setRsltMsg(String rsltMsg) {
        this.rsltMsg = rsltMsg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunear_draw.STATUS
     *
     * @return the value of yunear_draw.STATUS
     *
     * @mbggenerated Wed Sep 28 11:17:07 CST 2016
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunear_draw.STATUS
     *
     * @param status the value for yunear_draw.STATUS
     *
     * @mbggenerated Wed Sep 28 11:17:07 CST 2016
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunear_draw.DATE_CREATE
     *
     * @return the value of yunear_draw.DATE_CREATE
     *
     * @mbggenerated Wed Sep 28 11:17:07 CST 2016
     */
    public Date getDateCreate() {
        return dateCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunear_draw.DATE_CREATE
     *
     * @param dateCreate the value for yunear_draw.DATE_CREATE
     *
     * @mbggenerated Wed Sep 28 11:17:07 CST 2016
     */
    public void setDateCreate(Date dateCreate) {
        this.dateCreate = dateCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunear_draw.DATE_STATUS
     *
     * @return the value of yunear_draw.DATE_STATUS
     *
     * @mbggenerated Wed Sep 28 11:17:07 CST 2016
     */
    public Date getDateStatus() {
        return dateStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunear_draw.DATE_STATUS
     *
     * @param dateStatus the value for yunear_draw.DATE_STATUS
     *
     * @mbggenerated Wed Sep 28 11:17:07 CST 2016
     */
    public void setDateStatus(Date dateStatus) {
        this.dateStatus = dateStatus;
    }
}