package com.kakasure.bqf.dao.model;

import java.util.Date;

public class Labels {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunear_labels.LABEL_ID
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    private String labelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunear_labels.VIDEO_CATEGORY_ID
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    private String videoCategoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunear_labels.COPYRIGHTMULTI_ID
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    private String copyrightmultiId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunear_labels.LABEL_NAME
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    private String labelName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunear_labels.LABEL_CLICKS_NUM
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    private Integer labelClicksNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunear_labels.DATE_CREATE
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    private Date dateCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunear_labels.DATE_MODIFY
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    private Date dateModify;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunear_labels.LABEL_ID
     *
     * @return the value of yunear_labels.LABEL_ID
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    public String getLabelId() {
        return labelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunear_labels.LABEL_ID
     *
     * @param labelId the value for yunear_labels.LABEL_ID
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    public void setLabelId(String labelId) {
        this.labelId = labelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunear_labels.VIDEO_CATEGORY_ID
     *
     * @return the value of yunear_labels.VIDEO_CATEGORY_ID
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    public String getVideoCategoryId() {
        return videoCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunear_labels.VIDEO_CATEGORY_ID
     *
     * @param videoCategoryId the value for yunear_labels.VIDEO_CATEGORY_ID
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    public void setVideoCategoryId(String videoCategoryId) {
        this.videoCategoryId = videoCategoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunear_labels.COPYRIGHTMULTI_ID
     *
     * @return the value of yunear_labels.COPYRIGHTMULTI_ID
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    public String getCopyrightmultiId() {
        return copyrightmultiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunear_labels.COPYRIGHTMULTI_ID
     *
     * @param copyrightmultiId the value for yunear_labels.COPYRIGHTMULTI_ID
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    public void setCopyrightmultiId(String copyrightmultiId) {
        this.copyrightmultiId = copyrightmultiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunear_labels.LABEL_NAME
     *
     * @return the value of yunear_labels.LABEL_NAME
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    public String getLabelName() {
        return labelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunear_labels.LABEL_NAME
     *
     * @param labelName the value for yunear_labels.LABEL_NAME
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    public void setLabelName(String labelName) {
        this.labelName = labelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunear_labels.LABEL_CLICKS_NUM
     *
     * @return the value of yunear_labels.LABEL_CLICKS_NUM
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    public Integer getLabelClicksNum() {
        return labelClicksNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunear_labels.LABEL_CLICKS_NUM
     *
     * @param labelClicksNum the value for yunear_labels.LABEL_CLICKS_NUM
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    public void setLabelClicksNum(Integer labelClicksNum) {
        this.labelClicksNum = labelClicksNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunear_labels.DATE_CREATE
     *
     * @return the value of yunear_labels.DATE_CREATE
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    public Date getDateCreate() {
        return dateCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunear_labels.DATE_CREATE
     *
     * @param dateCreate the value for yunear_labels.DATE_CREATE
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    public void setDateCreate(Date dateCreate) {
        this.dateCreate = dateCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunear_labels.DATE_MODIFY
     *
     * @return the value of yunear_labels.DATE_MODIFY
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    public Date getDateModify() {
        return dateModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunear_labels.DATE_MODIFY
     *
     * @param dateModify the value for yunear_labels.DATE_MODIFY
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    public void setDateModify(Date dateModify) {
        this.dateModify = dateModify;
    }
}