package com.kakasure.bqf.dao.model;

import java.math.BigDecimal;
import java.util.Date;

public class LiveBqfGift {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunear_live_bqf_gift.id
     *
     * @mbggenerated Wed Sep 28 16:07:35 CST 2016
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunear_live_bqf_gift.live_affiliate_gift_id
     *
     * @mbggenerated Wed Sep 28 16:07:35 CST 2016
     */
    private Long liveAffiliateGiftId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunear_live_bqf_gift.gift_num
     *
     * @mbggenerated Wed Sep 28 16:07:35 CST 2016
     */
    private Integer giftNum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunear_live_bqf_gift.gift_name
     *
     * @mbggenerated Wed Sep 28 16:07:35 CST 2016
     */
    private String giftName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunear_live_bqf_gift.copyright_webcast_id
     *
     * @mbggenerated Wed Sep 28 16:07:35 CST 2016
     */
    private String copyrightWebcastId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunear_live_bqf_gift.copyright_user_id
     *
     * @mbggenerated Wed Sep 28 16:07:35 CST 2016
     */
    private String copyrightUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunear_live_bqf_gift.cash_copyright
     *
     * @mbggenerated Wed Sep 28 16:07:35 CST 2016
     */
    private BigDecimal cashCopyright;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunear_live_bqf_gift.username_copyright
     *
     * @mbggenerated Wed Sep 28 16:07:35 CST 2016
     */
    private String usernameCopyright;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunear_live_bqf_gift.point_copyright
     *
     * @mbggenerated Wed Sep 28 16:07:35 CST 2016
     */
    private Integer pointCopyright;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunear_live_bqf_gift.date_create
     *
     * @mbggenerated Wed Sep 28 16:07:35 CST 2016
     */
    private Date dateCreate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunear_live_bqf_gift.id
     *
     * @return the value of yunear_live_bqf_gift.id
     *
     * @mbggenerated Wed Sep 28 16:07:35 CST 2016
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunear_live_bqf_gift.id
     *
     * @param id the value for yunear_live_bqf_gift.id
     *
     * @mbggenerated Wed Sep 28 16:07:35 CST 2016
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunear_live_bqf_gift.live_affiliate_gift_id
     *
     * @return the value of yunear_live_bqf_gift.live_affiliate_gift_id
     *
     * @mbggenerated Wed Sep 28 16:07:35 CST 2016
     */
    public Long getLiveAffiliateGiftId() {
        return liveAffiliateGiftId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunear_live_bqf_gift.live_affiliate_gift_id
     *
     * @param liveAffiliateGiftId the value for yunear_live_bqf_gift.live_affiliate_gift_id
     *
     * @mbggenerated Wed Sep 28 16:07:35 CST 2016
     */
    public void setLiveAffiliateGiftId(Long liveAffiliateGiftId) {
        this.liveAffiliateGiftId = liveAffiliateGiftId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunear_live_bqf_gift.gift_num
     *
     * @return the value of yunear_live_bqf_gift.gift_num
     *
     * @mbggenerated Wed Sep 28 16:07:35 CST 2016
     */
    public Integer getGiftNum() {
        return giftNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunear_live_bqf_gift.gift_num
     *
     * @param giftNum the value for yunear_live_bqf_gift.gift_num
     *
     * @mbggenerated Wed Sep 28 16:07:35 CST 2016
     */
    public void setGiftNum(Integer giftNum) {
        this.giftNum = giftNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunear_live_bqf_gift.gift_name
     *
     * @return the value of yunear_live_bqf_gift.gift_name
     *
     * @mbggenerated Wed Sep 28 16:07:35 CST 2016
     */
    public String getGiftName() {
        return giftName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunear_live_bqf_gift.gift_name
     *
     * @param giftName the value for yunear_live_bqf_gift.gift_name
     *
     * @mbggenerated Wed Sep 28 16:07:35 CST 2016
     */
    public void setGiftName(String giftName) {
        this.giftName = giftName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunear_live_bqf_gift.copyright_webcast_id
     *
     * @return the value of yunear_live_bqf_gift.copyright_webcast_id
     *
     * @mbggenerated Wed Sep 28 16:07:35 CST 2016
     */
    public String getCopyrightWebcastId() {
        return copyrightWebcastId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunear_live_bqf_gift.copyright_webcast_id
     *
     * @param copyrightWebcastId the value for yunear_live_bqf_gift.copyright_webcast_id
     *
     * @mbggenerated Wed Sep 28 16:07:35 CST 2016
     */
    public void setCopyrightWebcastId(String copyrightWebcastId) {
        this.copyrightWebcastId = copyrightWebcastId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunear_live_bqf_gift.copyright_user_id
     *
     * @return the value of yunear_live_bqf_gift.copyright_user_id
     *
     * @mbggenerated Wed Sep 28 16:07:35 CST 2016
     */
    public String getCopyrightUserId() {
        return copyrightUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunear_live_bqf_gift.copyright_user_id
     *
     * @param copyrightUserId the value for yunear_live_bqf_gift.copyright_user_id
     *
     * @mbggenerated Wed Sep 28 16:07:35 CST 2016
     */
    public void setCopyrightUserId(String copyrightUserId) {
        this.copyrightUserId = copyrightUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunear_live_bqf_gift.cash_copyright
     *
     * @return the value of yunear_live_bqf_gift.cash_copyright
     *
     * @mbggenerated Wed Sep 28 16:07:35 CST 2016
     */
    public BigDecimal getCashCopyright() {
        return cashCopyright;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunear_live_bqf_gift.cash_copyright
     *
     * @param cashCopyright the value for yunear_live_bqf_gift.cash_copyright
     *
     * @mbggenerated Wed Sep 28 16:07:35 CST 2016
     */
    public void setCashCopyright(BigDecimal cashCopyright) {
        this.cashCopyright = cashCopyright;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunear_live_bqf_gift.username_copyright
     *
     * @return the value of yunear_live_bqf_gift.username_copyright
     *
     * @mbggenerated Wed Sep 28 16:07:35 CST 2016
     */
    public String getUsernameCopyright() {
        return usernameCopyright;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunear_live_bqf_gift.username_copyright
     *
     * @param usernameCopyright the value for yunear_live_bqf_gift.username_copyright
     *
     * @mbggenerated Wed Sep 28 16:07:35 CST 2016
     */
    public void setUsernameCopyright(String usernameCopyright) {
        this.usernameCopyright = usernameCopyright;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunear_live_bqf_gift.point_copyright
     *
     * @return the value of yunear_live_bqf_gift.point_copyright
     *
     * @mbggenerated Wed Sep 28 16:07:35 CST 2016
     */
    public Integer getPointCopyright() {
        return pointCopyright;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunear_live_bqf_gift.point_copyright
     *
     * @param pointCopyright the value for yunear_live_bqf_gift.point_copyright
     *
     * @mbggenerated Wed Sep 28 16:07:35 CST 2016
     */
    public void setPointCopyright(Integer pointCopyright) {
        this.pointCopyright = pointCopyright;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunear_live_bqf_gift.date_create
     *
     * @return the value of yunear_live_bqf_gift.date_create
     *
     * @mbggenerated Wed Sep 28 16:07:35 CST 2016
     */
    public Date getDateCreate() {
        return dateCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunear_live_bqf_gift.date_create
     *
     * @param dateCreate the value for yunear_live_bqf_gift.date_create
     *
     * @mbggenerated Wed Sep 28 16:07:35 CST 2016
     */
    public void setDateCreate(Date dateCreate) {
        this.dateCreate = dateCreate;
    }
}