package com.kakasure.bqf.dao.model;

import java.util.Date;

public class LiveBroadcast {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunear_live_broadcast.LIVE_BROADCAST_ID
     *
     * @mbggenerated Wed Nov 09 15:01:33 GMT+08:00 2016
     */
    private String liveBroadcastId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunear_live_broadcast.NAME
     *
     * @mbggenerated Wed Nov 09 15:01:33 GMT+08:00 2016
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunear_live_broadcast.CHANNEL_TYPE
     *
     * @mbggenerated Wed Nov 09 15:01:33 GMT+08:00 2016
     */
    private String channelType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunear_live_broadcast.WEBCAST_ID
     *
     * @mbggenerated Wed Nov 09 15:01:33 GMT+08:00 2016
     */
    private String webcastId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunear_live_broadcast.WEBCAST_NUMBER
     *
     * @mbggenerated Wed Nov 09 15:01:33 GMT+08:00 2016
     */
    private String webcastNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunear_live_broadcast.DATE_START_TIME
     *
     * @mbggenerated Wed Nov 09 15:01:33 GMT+08:00 2016
     */
    private Date dateStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunear_live_broadcast.DATE_END_TIME
     *
     * @mbggenerated Wed Nov 09 15:01:33 GMT+08:00 2016
     */
    private Date dateEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunear_live_broadcast.DATE_START_INTERVAL
     *
     * @mbggenerated Wed Nov 09 15:01:33 GMT+08:00 2016
     */
    private Integer dateStartInterval;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunear_live_broadcast.DATE_END_INTERVAL
     *
     * @mbggenerated Wed Nov 09 15:01:33 GMT+08:00 2016
     */
    private Integer dateEndInterval;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunear_live_broadcast.PAY_TYPE
     *
     * @mbggenerated Wed Nov 09 15:01:33 GMT+08:00 2016
     */
    private String payType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunear_live_broadcast.PRODUCT_CONCESSION
     *
     * @mbggenerated Wed Nov 09 15:01:33 GMT+08:00 2016
     */
    private Double productConcession;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunear_live_broadcast.PICTURE_PATH
     *
     * @mbggenerated Wed Nov 09 15:01:33 GMT+08:00 2016
     */
    private String picturePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunear_live_broadcast.DESCR
     *
     * @mbggenerated Wed Nov 09 15:01:33 GMT+08:00 2016
     */
    private String descr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunear_live_broadcast.ANCHOR_PATH
     *
     * @mbggenerated Wed Nov 09 15:01:33 GMT+08:00 2016
     */
    private String anchorPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunear_live_broadcast.GUESTS_PATH
     *
     * @mbggenerated Wed Nov 09 15:01:33 GMT+08:00 2016
     */
    private String guestsPath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunear_live_broadcast.GUESTS_CODE_PATH
     *
     * @mbggenerated Wed Nov 09 15:01:33 GMT+08:00 2016
     */
    private String guestsCodePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunear_live_broadcast.ANCHOR_PASSWORD
     *
     * @mbggenerated Wed Nov 09 15:01:33 GMT+08:00 2016
     */
    private Integer anchorPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunear_live_broadcast.GUESTS_PASSWORD
     *
     * @mbggenerated Wed Nov 09 15:01:33 GMT+08:00 2016
     */
    private Integer guestsPassword;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunear_live_broadcast.ATTENDEE_PATH
     *
     * @mbggenerated Wed Nov 09 15:01:33 GMT+08:00 2016
     */
    private String attendeePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunear_live_broadcast.DATE_CREATE
     *
     * @mbggenerated Wed Nov 09 15:01:33 GMT+08:00 2016
     */
    private Date dateCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunear_live_broadcast.IS_DELETE
     *
     * @mbggenerated Wed Nov 09 15:01:33 GMT+08:00 2016
     */
    private String isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunear_live_broadcast.USER_ID
     *
     * @mbggenerated Wed Nov 09 15:01:33 GMT+08:00 2016
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunear_live_broadcast.PRICE
     *
     * @mbggenerated Wed Nov 09 15:01:33 GMT+08:00 2016
     */
    private Double price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunear_live_broadcast.LIVE_STATUS
     *
     * @mbggenerated Wed Nov 09 15:01:33 GMT+08:00 2016
     */
    private String liveStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunear_live_broadcast.LIVE_BROADCAST_ID
     *
     * @return the value of yunear_live_broadcast.LIVE_BROADCAST_ID
     *
     * @mbggenerated Wed Nov 09 15:01:33 GMT+08:00 2016
     */
    public String getLiveBroadcastId() {
        return liveBroadcastId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunear_live_broadcast.LIVE_BROADCAST_ID
     *
     * @param liveBroadcastId the value for yunear_live_broadcast.LIVE_BROADCAST_ID
     *
     * @mbggenerated Wed Nov 09 15:01:33 GMT+08:00 2016
     */
    public void setLiveBroadcastId(String liveBroadcastId) {
        this.liveBroadcastId = liveBroadcastId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunear_live_broadcast.NAME
     *
     * @return the value of yunear_live_broadcast.NAME
     *
     * @mbggenerated Wed Nov 09 15:01:33 GMT+08:00 2016
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunear_live_broadcast.NAME
     *
     * @param name the value for yunear_live_broadcast.NAME
     *
     * @mbggenerated Wed Nov 09 15:01:33 GMT+08:00 2016
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunear_live_broadcast.CHANNEL_TYPE
     *
     * @return the value of yunear_live_broadcast.CHANNEL_TYPE
     *
     * @mbggenerated Wed Nov 09 15:01:33 GMT+08:00 2016
     */
    public String getChannelType() {
        return channelType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunear_live_broadcast.CHANNEL_TYPE
     *
     * @param channelType the value for yunear_live_broadcast.CHANNEL_TYPE
     *
     * @mbggenerated Wed Nov 09 15:01:33 GMT+08:00 2016
     */
    public void setChannelType(String channelType) {
        this.channelType = channelType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunear_live_broadcast.WEBCAST_ID
     *
     * @return the value of yunear_live_broadcast.WEBCAST_ID
     *
     * @mbggenerated Wed Nov 09 15:01:33 GMT+08:00 2016
     */
    public String getWebcastId() {
        return webcastId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunear_live_broadcast.WEBCAST_ID
     *
     * @param webcastId the value for yunear_live_broadcast.WEBCAST_ID
     *
     * @mbggenerated Wed Nov 09 15:01:33 GMT+08:00 2016
     */
    public void setWebcastId(String webcastId) {
        this.webcastId = webcastId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunear_live_broadcast.WEBCAST_NUMBER
     *
     * @return the value of yunear_live_broadcast.WEBCAST_NUMBER
     *
     * @mbggenerated Wed Nov 09 15:01:33 GMT+08:00 2016
     */
    public String getWebcastNumber() {
        return webcastNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunear_live_broadcast.WEBCAST_NUMBER
     *
     * @param webcastNumber the value for yunear_live_broadcast.WEBCAST_NUMBER
     *
     * @mbggenerated Wed Nov 09 15:01:33 GMT+08:00 2016
     */
    public void setWebcastNumber(String webcastNumber) {
        this.webcastNumber = webcastNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunear_live_broadcast.DATE_START_TIME
     *
     * @return the value of yunear_live_broadcast.DATE_START_TIME
     *
     * @mbggenerated Wed Nov 09 15:01:33 GMT+08:00 2016
     */
    public Date getDateStartTime() {
        return dateStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunear_live_broadcast.DATE_START_TIME
     *
     * @param dateStartTime the value for yunear_live_broadcast.DATE_START_TIME
     *
     * @mbggenerated Wed Nov 09 15:01:33 GMT+08:00 2016
     */
    public void setDateStartTime(Date dateStartTime) {
        this.dateStartTime = dateStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunear_live_broadcast.DATE_END_TIME
     *
     * @return the value of yunear_live_broadcast.DATE_END_TIME
     *
     * @mbggenerated Wed Nov 09 15:01:33 GMT+08:00 2016
     */
    public Date getDateEndTime() {
        return dateEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunear_live_broadcast.DATE_END_TIME
     *
     * @param dateEndTime the value for yunear_live_broadcast.DATE_END_TIME
     *
     * @mbggenerated Wed Nov 09 15:01:33 GMT+08:00 2016
     */
    public void setDateEndTime(Date dateEndTime) {
        this.dateEndTime = dateEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunear_live_broadcast.DATE_START_INTERVAL
     *
     * @return the value of yunear_live_broadcast.DATE_START_INTERVAL
     *
     * @mbggenerated Wed Nov 09 15:01:33 GMT+08:00 2016
     */
    public Integer getDateStartInterval() {
        return dateStartInterval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunear_live_broadcast.DATE_START_INTERVAL
     *
     * @param dateStartInterval the value for yunear_live_broadcast.DATE_START_INTERVAL
     *
     * @mbggenerated Wed Nov 09 15:01:33 GMT+08:00 2016
     */
    public void setDateStartInterval(Integer dateStartInterval) {
        this.dateStartInterval = dateStartInterval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunear_live_broadcast.DATE_END_INTERVAL
     *
     * @return the value of yunear_live_broadcast.DATE_END_INTERVAL
     *
     * @mbggenerated Wed Nov 09 15:01:33 GMT+08:00 2016
     */
    public Integer getDateEndInterval() {
        return dateEndInterval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunear_live_broadcast.DATE_END_INTERVAL
     *
     * @param dateEndInterval the value for yunear_live_broadcast.DATE_END_INTERVAL
     *
     * @mbggenerated Wed Nov 09 15:01:33 GMT+08:00 2016
     */
    public void setDateEndInterval(Integer dateEndInterval) {
        this.dateEndInterval = dateEndInterval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunear_live_broadcast.PAY_TYPE
     *
     * @return the value of yunear_live_broadcast.PAY_TYPE
     *
     * @mbggenerated Wed Nov 09 15:01:33 GMT+08:00 2016
     */
    public String getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunear_live_broadcast.PAY_TYPE
     *
     * @param payType the value for yunear_live_broadcast.PAY_TYPE
     *
     * @mbggenerated Wed Nov 09 15:01:33 GMT+08:00 2016
     */
    public void setPayType(String payType) {
        this.payType = payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunear_live_broadcast.PRODUCT_CONCESSION
     *
     * @return the value of yunear_live_broadcast.PRODUCT_CONCESSION
     *
     * @mbggenerated Wed Nov 09 15:01:33 GMT+08:00 2016
     */
    public Double getProductConcession() {
        return productConcession;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunear_live_broadcast.PRODUCT_CONCESSION
     *
     * @param productConcession the value for yunear_live_broadcast.PRODUCT_CONCESSION
     *
     * @mbggenerated Wed Nov 09 15:01:33 GMT+08:00 2016
     */
    public void setProductConcession(Double productConcession) {
        this.productConcession = productConcession;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunear_live_broadcast.PICTURE_PATH
     *
     * @return the value of yunear_live_broadcast.PICTURE_PATH
     *
     * @mbggenerated Wed Nov 09 15:01:33 GMT+08:00 2016
     */
    public String getPicturePath() {
        return picturePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunear_live_broadcast.PICTURE_PATH
     *
     * @param picturePath the value for yunear_live_broadcast.PICTURE_PATH
     *
     * @mbggenerated Wed Nov 09 15:01:33 GMT+08:00 2016
     */
    public void setPicturePath(String picturePath) {
        this.picturePath = picturePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunear_live_broadcast.DESCR
     *
     * @return the value of yunear_live_broadcast.DESCR
     *
     * @mbggenerated Wed Nov 09 15:01:33 GMT+08:00 2016
     */
    public String getDescr() {
        return descr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunear_live_broadcast.DESCR
     *
     * @param descr the value for yunear_live_broadcast.DESCR
     *
     * @mbggenerated Wed Nov 09 15:01:33 GMT+08:00 2016
     */
    public void setDescr(String descr) {
        this.descr = descr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunear_live_broadcast.ANCHOR_PATH
     *
     * @return the value of yunear_live_broadcast.ANCHOR_PATH
     *
     * @mbggenerated Wed Nov 09 15:01:33 GMT+08:00 2016
     */
    public String getAnchorPath() {
        return anchorPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunear_live_broadcast.ANCHOR_PATH
     *
     * @param anchorPath the value for yunear_live_broadcast.ANCHOR_PATH
     *
     * @mbggenerated Wed Nov 09 15:01:33 GMT+08:00 2016
     */
    public void setAnchorPath(String anchorPath) {
        this.anchorPath = anchorPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunear_live_broadcast.GUESTS_PATH
     *
     * @return the value of yunear_live_broadcast.GUESTS_PATH
     *
     * @mbggenerated Wed Nov 09 15:01:33 GMT+08:00 2016
     */
    public String getGuestsPath() {
        return guestsPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunear_live_broadcast.GUESTS_PATH
     *
     * @param guestsPath the value for yunear_live_broadcast.GUESTS_PATH
     *
     * @mbggenerated Wed Nov 09 15:01:33 GMT+08:00 2016
     */
    public void setGuestsPath(String guestsPath) {
        this.guestsPath = guestsPath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunear_live_broadcast.GUESTS_CODE_PATH
     *
     * @return the value of yunear_live_broadcast.GUESTS_CODE_PATH
     *
     * @mbggenerated Wed Nov 09 15:01:33 GMT+08:00 2016
     */
    public String getGuestsCodePath() {
        return guestsCodePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunear_live_broadcast.GUESTS_CODE_PATH
     *
     * @param guestsCodePath the value for yunear_live_broadcast.GUESTS_CODE_PATH
     *
     * @mbggenerated Wed Nov 09 15:01:33 GMT+08:00 2016
     */
    public void setGuestsCodePath(String guestsCodePath) {
        this.guestsCodePath = guestsCodePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunear_live_broadcast.ANCHOR_PASSWORD
     *
     * @return the value of yunear_live_broadcast.ANCHOR_PASSWORD
     *
     * @mbggenerated Wed Nov 09 15:01:33 GMT+08:00 2016
     */
    public Integer getAnchorPassword() {
        return anchorPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunear_live_broadcast.ANCHOR_PASSWORD
     *
     * @param anchorPassword the value for yunear_live_broadcast.ANCHOR_PASSWORD
     *
     * @mbggenerated Wed Nov 09 15:01:33 GMT+08:00 2016
     */
    public void setAnchorPassword(Integer anchorPassword) {
        this.anchorPassword = anchorPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunear_live_broadcast.GUESTS_PASSWORD
     *
     * @return the value of yunear_live_broadcast.GUESTS_PASSWORD
     *
     * @mbggenerated Wed Nov 09 15:01:33 GMT+08:00 2016
     */
    public Integer getGuestsPassword() {
        return guestsPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunear_live_broadcast.GUESTS_PASSWORD
     *
     * @param guestsPassword the value for yunear_live_broadcast.GUESTS_PASSWORD
     *
     * @mbggenerated Wed Nov 09 15:01:33 GMT+08:00 2016
     */
    public void setGuestsPassword(Integer guestsPassword) {
        this.guestsPassword = guestsPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunear_live_broadcast.ATTENDEE_PATH
     *
     * @return the value of yunear_live_broadcast.ATTENDEE_PATH
     *
     * @mbggenerated Wed Nov 09 15:01:33 GMT+08:00 2016
     */
    public String getAttendeePath() {
        return attendeePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunear_live_broadcast.ATTENDEE_PATH
     *
     * @param attendeePath the value for yunear_live_broadcast.ATTENDEE_PATH
     *
     * @mbggenerated Wed Nov 09 15:01:33 GMT+08:00 2016
     */
    public void setAttendeePath(String attendeePath) {
        this.attendeePath = attendeePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunear_live_broadcast.DATE_CREATE
     *
     * @return the value of yunear_live_broadcast.DATE_CREATE
     *
     * @mbggenerated Wed Nov 09 15:01:33 GMT+08:00 2016
     */
    public Date getDateCreate() {
        return dateCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunear_live_broadcast.DATE_CREATE
     *
     * @param dateCreate the value for yunear_live_broadcast.DATE_CREATE
     *
     * @mbggenerated Wed Nov 09 15:01:33 GMT+08:00 2016
     */
    public void setDateCreate(Date dateCreate) {
        this.dateCreate = dateCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunear_live_broadcast.IS_DELETE
     *
     * @return the value of yunear_live_broadcast.IS_DELETE
     *
     * @mbggenerated Wed Nov 09 15:01:33 GMT+08:00 2016
     */
    public String getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunear_live_broadcast.IS_DELETE
     *
     * @param isDelete the value for yunear_live_broadcast.IS_DELETE
     *
     * @mbggenerated Wed Nov 09 15:01:33 GMT+08:00 2016
     */
    public void setIsDelete(String isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunear_live_broadcast.USER_ID
     *
     * @return the value of yunear_live_broadcast.USER_ID
     *
     * @mbggenerated Wed Nov 09 15:01:33 GMT+08:00 2016
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunear_live_broadcast.USER_ID
     *
     * @param userId the value for yunear_live_broadcast.USER_ID
     *
     * @mbggenerated Wed Nov 09 15:01:33 GMT+08:00 2016
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunear_live_broadcast.PRICE
     *
     * @return the value of yunear_live_broadcast.PRICE
     *
     * @mbggenerated Wed Nov 09 15:01:33 GMT+08:00 2016
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunear_live_broadcast.PRICE
     *
     * @param price the value for yunear_live_broadcast.PRICE
     *
     * @mbggenerated Wed Nov 09 15:01:33 GMT+08:00 2016
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunear_live_broadcast.LIVE_STATUS
     *
     * @return the value of yunear_live_broadcast.LIVE_STATUS
     *
     * @mbggenerated Wed Nov 09 15:01:33 GMT+08:00 2016
     */
    public String getLiveStatus() {
        return liveStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunear_live_broadcast.LIVE_STATUS
     *
     * @param liveStatus the value for yunear_live_broadcast.LIVE_STATUS
     *
     * @mbggenerated Wed Nov 09 15:01:33 GMT+08:00 2016
     */
    public void setLiveStatus(String liveStatus) {
        this.liveStatus = liveStatus;
    }
}