package com.kakasure.bqf.dao.model;

import java.util.Date;

public class Message {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunear_message.MESSAGE_ID
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    private String messageId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunear_message.MEDIA_ID
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    private String mediaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunear_message.TYPE
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunear_message.CONTENT
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunear_message.DATE_CREATE
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    private Date dateCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunear_message.DATE_MODIFY
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    private Date dateModify;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunear_message.IS_DELETE
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    private String isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunear_message.MESSAGE_ID
     *
     * @return the value of yunear_message.MESSAGE_ID
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    public String getMessageId() {
        return messageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunear_message.MESSAGE_ID
     *
     * @param messageId the value for yunear_message.MESSAGE_ID
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    public void setMessageId(String messageId) {
        this.messageId = messageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunear_message.MEDIA_ID
     *
     * @return the value of yunear_message.MEDIA_ID
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    public String getMediaId() {
        return mediaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunear_message.MEDIA_ID
     *
     * @param mediaId the value for yunear_message.MEDIA_ID
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    public void setMediaId(String mediaId) {
        this.mediaId = mediaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunear_message.TYPE
     *
     * @return the value of yunear_message.TYPE
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunear_message.TYPE
     *
     * @param type the value for yunear_message.TYPE
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    public void setType(String type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunear_message.CONTENT
     *
     * @return the value of yunear_message.CONTENT
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunear_message.CONTENT
     *
     * @param content the value for yunear_message.CONTENT
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunear_message.DATE_CREATE
     *
     * @return the value of yunear_message.DATE_CREATE
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    public Date getDateCreate() {
        return dateCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunear_message.DATE_CREATE
     *
     * @param dateCreate the value for yunear_message.DATE_CREATE
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    public void setDateCreate(Date dateCreate) {
        this.dateCreate = dateCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunear_message.DATE_MODIFY
     *
     * @return the value of yunear_message.DATE_MODIFY
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    public Date getDateModify() {
        return dateModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunear_message.DATE_MODIFY
     *
     * @param dateModify the value for yunear_message.DATE_MODIFY
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    public void setDateModify(Date dateModify) {
        this.dateModify = dateModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunear_message.IS_DELETE
     *
     * @return the value of yunear_message.IS_DELETE
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    public String getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunear_message.IS_DELETE
     *
     * @param isDelete the value for yunear_message.IS_DELETE
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    public void setIsDelete(String isDelete) {
        this.isDelete = isDelete;
    }
}