package com.kakasure.bqf.dao.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class OrderExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table yunear_order
     *
     * @mbggenerated Sat Oct 15 10:03:07 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table yunear_order
     *
     * @mbggenerated Sat Oct 15 10:03:07 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table yunear_order
     *
     * @mbggenerated Sat Oct 15 10:03:07 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunear_order
     *
     * @mbggenerated Sat Oct 15 10:03:07 CST 2016
     */
    public OrderExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunear_order
     *
     * @mbggenerated Sat Oct 15 10:03:07 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunear_order
     *
     * @mbggenerated Sat Oct 15 10:03:07 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunear_order
     *
     * @mbggenerated Sat Oct 15 10:03:07 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunear_order
     *
     * @mbggenerated Sat Oct 15 10:03:07 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunear_order
     *
     * @mbggenerated Sat Oct 15 10:03:07 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunear_order
     *
     * @mbggenerated Sat Oct 15 10:03:07 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunear_order
     *
     * @mbggenerated Sat Oct 15 10:03:07 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunear_order
     *
     * @mbggenerated Sat Oct 15 10:03:07 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunear_order
     *
     * @mbggenerated Sat Oct 15 10:03:07 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunear_order
     *
     * @mbggenerated Sat Oct 15 10:03:07 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table yunear_order
     *
     * @mbggenerated Sat Oct 15 10:03:07 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andOrderIdIsNull() {
            addCriterion("ORDER_ID is null");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNotNull() {
            addCriterion("ORDER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andOrderIdEqualTo(String value) {
            addCriterion("ORDER_ID =", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotEqualTo(String value) {
            addCriterion("ORDER_ID <>", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThan(String value) {
            addCriterion("ORDER_ID >", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThanOrEqualTo(String value) {
            addCriterion("ORDER_ID >=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThan(String value) {
            addCriterion("ORDER_ID <", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThanOrEqualTo(String value) {
            addCriterion("ORDER_ID <=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLike(String value) {
            addCriterion("ORDER_ID like", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotLike(String value) {
            addCriterion("ORDER_ID not like", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdIn(List<String> values) {
            addCriterion("ORDER_ID in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotIn(List<String> values) {
            addCriterion("ORDER_ID not in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdBetween(String value1, String value2) {
            addCriterion("ORDER_ID between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotBetween(String value1, String value2) {
            addCriterion("ORDER_ID not between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderNumberIsNull() {
            addCriterion("ORDER_NUMBER is null");
            return (Criteria) this;
        }

        public Criteria andOrderNumberIsNotNull() {
            addCriterion("ORDER_NUMBER is not null");
            return (Criteria) this;
        }

        public Criteria andOrderNumberEqualTo(String value) {
            addCriterion("ORDER_NUMBER =", value, "orderNumber");
            return (Criteria) this;
        }

        public Criteria andOrderNumberNotEqualTo(String value) {
            addCriterion("ORDER_NUMBER <>", value, "orderNumber");
            return (Criteria) this;
        }

        public Criteria andOrderNumberGreaterThan(String value) {
            addCriterion("ORDER_NUMBER >", value, "orderNumber");
            return (Criteria) this;
        }

        public Criteria andOrderNumberGreaterThanOrEqualTo(String value) {
            addCriterion("ORDER_NUMBER >=", value, "orderNumber");
            return (Criteria) this;
        }

        public Criteria andOrderNumberLessThan(String value) {
            addCriterion("ORDER_NUMBER <", value, "orderNumber");
            return (Criteria) this;
        }

        public Criteria andOrderNumberLessThanOrEqualTo(String value) {
            addCriterion("ORDER_NUMBER <=", value, "orderNumber");
            return (Criteria) this;
        }

        public Criteria andOrderNumberLike(String value) {
            addCriterion("ORDER_NUMBER like", value, "orderNumber");
            return (Criteria) this;
        }

        public Criteria andOrderNumberNotLike(String value) {
            addCriterion("ORDER_NUMBER not like", value, "orderNumber");
            return (Criteria) this;
        }

        public Criteria andOrderNumberIn(List<String> values) {
            addCriterion("ORDER_NUMBER in", values, "orderNumber");
            return (Criteria) this;
        }

        public Criteria andOrderNumberNotIn(List<String> values) {
            addCriterion("ORDER_NUMBER not in", values, "orderNumber");
            return (Criteria) this;
        }

        public Criteria andOrderNumberBetween(String value1, String value2) {
            addCriterion("ORDER_NUMBER between", value1, value2, "orderNumber");
            return (Criteria) this;
        }

        public Criteria andOrderNumberNotBetween(String value1, String value2) {
            addCriterion("ORDER_NUMBER not between", value1, value2, "orderNumber");
            return (Criteria) this;
        }

        public Criteria andTotalIsNull() {
            addCriterion("TOTAL is null");
            return (Criteria) this;
        }

        public Criteria andTotalIsNotNull() {
            addCriterion("TOTAL is not null");
            return (Criteria) this;
        }

        public Criteria andTotalEqualTo(Double value) {
            addCriterion("TOTAL =", value, "total");
            return (Criteria) this;
        }

        public Criteria andTotalNotEqualTo(Double value) {
            addCriterion("TOTAL <>", value, "total");
            return (Criteria) this;
        }

        public Criteria andTotalGreaterThan(Double value) {
            addCriterion("TOTAL >", value, "total");
            return (Criteria) this;
        }

        public Criteria andTotalGreaterThanOrEqualTo(Double value) {
            addCriterion("TOTAL >=", value, "total");
            return (Criteria) this;
        }

        public Criteria andTotalLessThan(Double value) {
            addCriterion("TOTAL <", value, "total");
            return (Criteria) this;
        }

        public Criteria andTotalLessThanOrEqualTo(Double value) {
            addCriterion("TOTAL <=", value, "total");
            return (Criteria) this;
        }

        public Criteria andTotalIn(List<Double> values) {
            addCriterion("TOTAL in", values, "total");
            return (Criteria) this;
        }

        public Criteria andTotalNotIn(List<Double> values) {
            addCriterion("TOTAL not in", values, "total");
            return (Criteria) this;
        }

        public Criteria andTotalBetween(Double value1, Double value2) {
            addCriterion("TOTAL between", value1, value2, "total");
            return (Criteria) this;
        }

        public Criteria andTotalNotBetween(Double value1, Double value2) {
            addCriterion("TOTAL not between", value1, value2, "total");
            return (Criteria) this;
        }

        public Criteria andCommisionIsNull() {
            addCriterion("COMMISION is null");
            return (Criteria) this;
        }

        public Criteria andCommisionIsNotNull() {
            addCriterion("COMMISION is not null");
            return (Criteria) this;
        }

        public Criteria andCommisionEqualTo(Double value) {
            addCriterion("COMMISION =", value, "commision");
            return (Criteria) this;
        }

        public Criteria andCommisionNotEqualTo(Double value) {
            addCriterion("COMMISION <>", value, "commision");
            return (Criteria) this;
        }

        public Criteria andCommisionGreaterThan(Double value) {
            addCriterion("COMMISION >", value, "commision");
            return (Criteria) this;
        }

        public Criteria andCommisionGreaterThanOrEqualTo(Double value) {
            addCriterion("COMMISION >=", value, "commision");
            return (Criteria) this;
        }

        public Criteria andCommisionLessThan(Double value) {
            addCriterion("COMMISION <", value, "commision");
            return (Criteria) this;
        }

        public Criteria andCommisionLessThanOrEqualTo(Double value) {
            addCriterion("COMMISION <=", value, "commision");
            return (Criteria) this;
        }

        public Criteria andCommisionIn(List<Double> values) {
            addCriterion("COMMISION in", values, "commision");
            return (Criteria) this;
        }

        public Criteria andCommisionNotIn(List<Double> values) {
            addCriterion("COMMISION not in", values, "commision");
            return (Criteria) this;
        }

        public Criteria andCommisionBetween(Double value1, Double value2) {
            addCriterion("COMMISION between", value1, value2, "commision");
            return (Criteria) this;
        }

        public Criteria andCommisionNotBetween(Double value1, Double value2) {
            addCriterion("COMMISION not between", value1, value2, "commision");
            return (Criteria) this;
        }

        public Criteria andProductIsNull() {
            addCriterion("PRODUCT is null");
            return (Criteria) this;
        }

        public Criteria andProductIsNotNull() {
            addCriterion("PRODUCT is not null");
            return (Criteria) this;
        }

        public Criteria andProductEqualTo(String value) {
            addCriterion("PRODUCT =", value, "product");
            return (Criteria) this;
        }

        public Criteria andProductNotEqualTo(String value) {
            addCriterion("PRODUCT <>", value, "product");
            return (Criteria) this;
        }

        public Criteria andProductGreaterThan(String value) {
            addCriterion("PRODUCT >", value, "product");
            return (Criteria) this;
        }

        public Criteria andProductGreaterThanOrEqualTo(String value) {
            addCriterion("PRODUCT >=", value, "product");
            return (Criteria) this;
        }

        public Criteria andProductLessThan(String value) {
            addCriterion("PRODUCT <", value, "product");
            return (Criteria) this;
        }

        public Criteria andProductLessThanOrEqualTo(String value) {
            addCriterion("PRODUCT <=", value, "product");
            return (Criteria) this;
        }

        public Criteria andProductLike(String value) {
            addCriterion("PRODUCT like", value, "product");
            return (Criteria) this;
        }

        public Criteria andProductNotLike(String value) {
            addCriterion("PRODUCT not like", value, "product");
            return (Criteria) this;
        }

        public Criteria andProductIn(List<String> values) {
            addCriterion("PRODUCT in", values, "product");
            return (Criteria) this;
        }

        public Criteria andProductNotIn(List<String> values) {
            addCriterion("PRODUCT not in", values, "product");
            return (Criteria) this;
        }

        public Criteria andProductBetween(String value1, String value2) {
            addCriterion("PRODUCT between", value1, value2, "product");
            return (Criteria) this;
        }

        public Criteria andProductNotBetween(String value1, String value2) {
            addCriterion("PRODUCT not between", value1, value2, "product");
            return (Criteria) this;
        }

        public Criteria andBuyUserIdIsNull() {
            addCriterion("BUY_USER_ID is null");
            return (Criteria) this;
        }

        public Criteria andBuyUserIdIsNotNull() {
            addCriterion("BUY_USER_ID is not null");
            return (Criteria) this;
        }

        public Criteria andBuyUserIdEqualTo(String value) {
            addCriterion("BUY_USER_ID =", value, "buyUserId");
            return (Criteria) this;
        }

        public Criteria andBuyUserIdNotEqualTo(String value) {
            addCriterion("BUY_USER_ID <>", value, "buyUserId");
            return (Criteria) this;
        }

        public Criteria andBuyUserIdGreaterThan(String value) {
            addCriterion("BUY_USER_ID >", value, "buyUserId");
            return (Criteria) this;
        }

        public Criteria andBuyUserIdGreaterThanOrEqualTo(String value) {
            addCriterion("BUY_USER_ID >=", value, "buyUserId");
            return (Criteria) this;
        }

        public Criteria andBuyUserIdLessThan(String value) {
            addCriterion("BUY_USER_ID <", value, "buyUserId");
            return (Criteria) this;
        }

        public Criteria andBuyUserIdLessThanOrEqualTo(String value) {
            addCriterion("BUY_USER_ID <=", value, "buyUserId");
            return (Criteria) this;
        }

        public Criteria andBuyUserIdLike(String value) {
            addCriterion("BUY_USER_ID like", value, "buyUserId");
            return (Criteria) this;
        }

        public Criteria andBuyUserIdNotLike(String value) {
            addCriterion("BUY_USER_ID not like", value, "buyUserId");
            return (Criteria) this;
        }

        public Criteria andBuyUserIdIn(List<String> values) {
            addCriterion("BUY_USER_ID in", values, "buyUserId");
            return (Criteria) this;
        }

        public Criteria andBuyUserIdNotIn(List<String> values) {
            addCriterion("BUY_USER_ID not in", values, "buyUserId");
            return (Criteria) this;
        }

        public Criteria andBuyUserIdBetween(String value1, String value2) {
            addCriterion("BUY_USER_ID between", value1, value2, "buyUserId");
            return (Criteria) this;
        }

        public Criteria andBuyUserIdNotBetween(String value1, String value2) {
            addCriterion("BUY_USER_ID not between", value1, value2, "buyUserId");
            return (Criteria) this;
        }

        public Criteria andBuyUserNameIsNull() {
            addCriterion("BUY_USER_NAME is null");
            return (Criteria) this;
        }

        public Criteria andBuyUserNameIsNotNull() {
            addCriterion("BUY_USER_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andBuyUserNameEqualTo(String value) {
            addCriterion("BUY_USER_NAME =", value, "buyUserName");
            return (Criteria) this;
        }

        public Criteria andBuyUserNameNotEqualTo(String value) {
            addCriterion("BUY_USER_NAME <>", value, "buyUserName");
            return (Criteria) this;
        }

        public Criteria andBuyUserNameGreaterThan(String value) {
            addCriterion("BUY_USER_NAME >", value, "buyUserName");
            return (Criteria) this;
        }

        public Criteria andBuyUserNameGreaterThanOrEqualTo(String value) {
            addCriterion("BUY_USER_NAME >=", value, "buyUserName");
            return (Criteria) this;
        }

        public Criteria andBuyUserNameLessThan(String value) {
            addCriterion("BUY_USER_NAME <", value, "buyUserName");
            return (Criteria) this;
        }

        public Criteria andBuyUserNameLessThanOrEqualTo(String value) {
            addCriterion("BUY_USER_NAME <=", value, "buyUserName");
            return (Criteria) this;
        }

        public Criteria andBuyUserNameLike(String value) {
            addCriterion("BUY_USER_NAME like", value, "buyUserName");
            return (Criteria) this;
        }

        public Criteria andBuyUserNameNotLike(String value) {
            addCriterion("BUY_USER_NAME not like", value, "buyUserName");
            return (Criteria) this;
        }

        public Criteria andBuyUserNameIn(List<String> values) {
            addCriterion("BUY_USER_NAME in", values, "buyUserName");
            return (Criteria) this;
        }

        public Criteria andBuyUserNameNotIn(List<String> values) {
            addCriterion("BUY_USER_NAME not in", values, "buyUserName");
            return (Criteria) this;
        }

        public Criteria andBuyUserNameBetween(String value1, String value2) {
            addCriterion("BUY_USER_NAME between", value1, value2, "buyUserName");
            return (Criteria) this;
        }

        public Criteria andBuyUserNameNotBetween(String value1, String value2) {
            addCriterion("BUY_USER_NAME not between", value1, value2, "buyUserName");
            return (Criteria) this;
        }

        public Criteria andMediaIdIsNull() {
            addCriterion("MEDIA_ID is null");
            return (Criteria) this;
        }

        public Criteria andMediaIdIsNotNull() {
            addCriterion("MEDIA_ID is not null");
            return (Criteria) this;
        }

        public Criteria andMediaIdEqualTo(String value) {
            addCriterion("MEDIA_ID =", value, "mediaId");
            return (Criteria) this;
        }

        public Criteria andMediaIdNotEqualTo(String value) {
            addCriterion("MEDIA_ID <>", value, "mediaId");
            return (Criteria) this;
        }

        public Criteria andMediaIdGreaterThan(String value) {
            addCriterion("MEDIA_ID >", value, "mediaId");
            return (Criteria) this;
        }

        public Criteria andMediaIdGreaterThanOrEqualTo(String value) {
            addCriterion("MEDIA_ID >=", value, "mediaId");
            return (Criteria) this;
        }

        public Criteria andMediaIdLessThan(String value) {
            addCriterion("MEDIA_ID <", value, "mediaId");
            return (Criteria) this;
        }

        public Criteria andMediaIdLessThanOrEqualTo(String value) {
            addCriterion("MEDIA_ID <=", value, "mediaId");
            return (Criteria) this;
        }

        public Criteria andMediaIdLike(String value) {
            addCriterion("MEDIA_ID like", value, "mediaId");
            return (Criteria) this;
        }

        public Criteria andMediaIdNotLike(String value) {
            addCriterion("MEDIA_ID not like", value, "mediaId");
            return (Criteria) this;
        }

        public Criteria andMediaIdIn(List<String> values) {
            addCriterion("MEDIA_ID in", values, "mediaId");
            return (Criteria) this;
        }

        public Criteria andMediaIdNotIn(List<String> values) {
            addCriterion("MEDIA_ID not in", values, "mediaId");
            return (Criteria) this;
        }

        public Criteria andMediaIdBetween(String value1, String value2) {
            addCriterion("MEDIA_ID between", value1, value2, "mediaId");
            return (Criteria) this;
        }

        public Criteria andMediaIdNotBetween(String value1, String value2) {
            addCriterion("MEDIA_ID not between", value1, value2, "mediaId");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("TYPE is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(Integer value) {
            addCriterion("TYPE =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(Integer value) {
            addCriterion("TYPE <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(Integer value) {
            addCriterion("TYPE >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("TYPE >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(Integer value) {
            addCriterion("TYPE <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(Integer value) {
            addCriterion("TYPE <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<Integer> values) {
            addCriterion("TYPE in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<Integer> values) {
            addCriterion("TYPE not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(Integer value1, Integer value2) {
            addCriterion("TYPE between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("TYPE not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andCopyrightIdIsNull() {
            addCriterion("COPYRIGHT_ID is null");
            return (Criteria) this;
        }

        public Criteria andCopyrightIdIsNotNull() {
            addCriterion("COPYRIGHT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCopyrightIdEqualTo(String value) {
            addCriterion("COPYRIGHT_ID =", value, "copyrightId");
            return (Criteria) this;
        }

        public Criteria andCopyrightIdNotEqualTo(String value) {
            addCriterion("COPYRIGHT_ID <>", value, "copyrightId");
            return (Criteria) this;
        }

        public Criteria andCopyrightIdGreaterThan(String value) {
            addCriterion("COPYRIGHT_ID >", value, "copyrightId");
            return (Criteria) this;
        }

        public Criteria andCopyrightIdGreaterThanOrEqualTo(String value) {
            addCriterion("COPYRIGHT_ID >=", value, "copyrightId");
            return (Criteria) this;
        }

        public Criteria andCopyrightIdLessThan(String value) {
            addCriterion("COPYRIGHT_ID <", value, "copyrightId");
            return (Criteria) this;
        }

        public Criteria andCopyrightIdLessThanOrEqualTo(String value) {
            addCriterion("COPYRIGHT_ID <=", value, "copyrightId");
            return (Criteria) this;
        }

        public Criteria andCopyrightIdLike(String value) {
            addCriterion("COPYRIGHT_ID like", value, "copyrightId");
            return (Criteria) this;
        }

        public Criteria andCopyrightIdNotLike(String value) {
            addCriterion("COPYRIGHT_ID not like", value, "copyrightId");
            return (Criteria) this;
        }

        public Criteria andCopyrightIdIn(List<String> values) {
            addCriterion("COPYRIGHT_ID in", values, "copyrightId");
            return (Criteria) this;
        }

        public Criteria andCopyrightIdNotIn(List<String> values) {
            addCriterion("COPYRIGHT_ID not in", values, "copyrightId");
            return (Criteria) this;
        }

        public Criteria andCopyrightIdBetween(String value1, String value2) {
            addCriterion("COPYRIGHT_ID between", value1, value2, "copyrightId");
            return (Criteria) this;
        }

        public Criteria andCopyrightIdNotBetween(String value1, String value2) {
            addCriterion("COPYRIGHT_ID not between", value1, value2, "copyrightId");
            return (Criteria) this;
        }

        public Criteria andPublishIdIsNull() {
            addCriterion("PUBLISH_ID is null");
            return (Criteria) this;
        }

        public Criteria andPublishIdIsNotNull() {
            addCriterion("PUBLISH_ID is not null");
            return (Criteria) this;
        }

        public Criteria andPublishIdEqualTo(String value) {
            addCriterion("PUBLISH_ID =", value, "publishId");
            return (Criteria) this;
        }

        public Criteria andPublishIdNotEqualTo(String value) {
            addCriterion("PUBLISH_ID <>", value, "publishId");
            return (Criteria) this;
        }

        public Criteria andPublishIdGreaterThan(String value) {
            addCriterion("PUBLISH_ID >", value, "publishId");
            return (Criteria) this;
        }

        public Criteria andPublishIdGreaterThanOrEqualTo(String value) {
            addCriterion("PUBLISH_ID >=", value, "publishId");
            return (Criteria) this;
        }

        public Criteria andPublishIdLessThan(String value) {
            addCriterion("PUBLISH_ID <", value, "publishId");
            return (Criteria) this;
        }

        public Criteria andPublishIdLessThanOrEqualTo(String value) {
            addCriterion("PUBLISH_ID <=", value, "publishId");
            return (Criteria) this;
        }

        public Criteria andPublishIdLike(String value) {
            addCriterion("PUBLISH_ID like", value, "publishId");
            return (Criteria) this;
        }

        public Criteria andPublishIdNotLike(String value) {
            addCriterion("PUBLISH_ID not like", value, "publishId");
            return (Criteria) this;
        }

        public Criteria andPublishIdIn(List<String> values) {
            addCriterion("PUBLISH_ID in", values, "publishId");
            return (Criteria) this;
        }

        public Criteria andPublishIdNotIn(List<String> values) {
            addCriterion("PUBLISH_ID not in", values, "publishId");
            return (Criteria) this;
        }

        public Criteria andPublishIdBetween(String value1, String value2) {
            addCriterion("PUBLISH_ID between", value1, value2, "publishId");
            return (Criteria) this;
        }

        public Criteria andPublishIdNotBetween(String value1, String value2) {
            addCriterion("PUBLISH_ID not between", value1, value2, "publishId");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("STATUS is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Integer value) {
            addCriterion("STATUS =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Integer value) {
            addCriterion("STATUS <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Integer value) {
            addCriterion("STATUS >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("STATUS >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Integer value) {
            addCriterion("STATUS <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Integer value) {
            addCriterion("STATUS <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Integer> values) {
            addCriterion("STATUS in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Integer> values) {
            addCriterion("STATUS not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Integer value1, Integer value2) {
            addCriterion("STATUS between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("STATUS not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andCashYunearIsNull() {
            addCriterion("CASH_YUNEAR is null");
            return (Criteria) this;
        }

        public Criteria andCashYunearIsNotNull() {
            addCriterion("CASH_YUNEAR is not null");
            return (Criteria) this;
        }

        public Criteria andCashYunearEqualTo(Double value) {
            addCriterion("CASH_YUNEAR =", value, "cashYunear");
            return (Criteria) this;
        }

        public Criteria andCashYunearNotEqualTo(Double value) {
            addCriterion("CASH_YUNEAR <>", value, "cashYunear");
            return (Criteria) this;
        }

        public Criteria andCashYunearGreaterThan(Double value) {
            addCriterion("CASH_YUNEAR >", value, "cashYunear");
            return (Criteria) this;
        }

        public Criteria andCashYunearGreaterThanOrEqualTo(Double value) {
            addCriterion("CASH_YUNEAR >=", value, "cashYunear");
            return (Criteria) this;
        }

        public Criteria andCashYunearLessThan(Double value) {
            addCriterion("CASH_YUNEAR <", value, "cashYunear");
            return (Criteria) this;
        }

        public Criteria andCashYunearLessThanOrEqualTo(Double value) {
            addCriterion("CASH_YUNEAR <=", value, "cashYunear");
            return (Criteria) this;
        }

        public Criteria andCashYunearIn(List<Double> values) {
            addCriterion("CASH_YUNEAR in", values, "cashYunear");
            return (Criteria) this;
        }

        public Criteria andCashYunearNotIn(List<Double> values) {
            addCriterion("CASH_YUNEAR not in", values, "cashYunear");
            return (Criteria) this;
        }

        public Criteria andCashYunearBetween(Double value1, Double value2) {
            addCriterion("CASH_YUNEAR between", value1, value2, "cashYunear");
            return (Criteria) this;
        }

        public Criteria andCashYunearNotBetween(Double value1, Double value2) {
            addCriterion("CASH_YUNEAR not between", value1, value2, "cashYunear");
            return (Criteria) this;
        }

        public Criteria andCashCopyrightIsNull() {
            addCriterion("CASH_COPYRIGHT is null");
            return (Criteria) this;
        }

        public Criteria andCashCopyrightIsNotNull() {
            addCriterion("CASH_COPYRIGHT is not null");
            return (Criteria) this;
        }

        public Criteria andCashCopyrightEqualTo(Double value) {
            addCriterion("CASH_COPYRIGHT =", value, "cashCopyright");
            return (Criteria) this;
        }

        public Criteria andCashCopyrightNotEqualTo(Double value) {
            addCriterion("CASH_COPYRIGHT <>", value, "cashCopyright");
            return (Criteria) this;
        }

        public Criteria andCashCopyrightGreaterThan(Double value) {
            addCriterion("CASH_COPYRIGHT >", value, "cashCopyright");
            return (Criteria) this;
        }

        public Criteria andCashCopyrightGreaterThanOrEqualTo(Double value) {
            addCriterion("CASH_COPYRIGHT >=", value, "cashCopyright");
            return (Criteria) this;
        }

        public Criteria andCashCopyrightLessThan(Double value) {
            addCriterion("CASH_COPYRIGHT <", value, "cashCopyright");
            return (Criteria) this;
        }

        public Criteria andCashCopyrightLessThanOrEqualTo(Double value) {
            addCriterion("CASH_COPYRIGHT <=", value, "cashCopyright");
            return (Criteria) this;
        }

        public Criteria andCashCopyrightIn(List<Double> values) {
            addCriterion("CASH_COPYRIGHT in", values, "cashCopyright");
            return (Criteria) this;
        }

        public Criteria andCashCopyrightNotIn(List<Double> values) {
            addCriterion("CASH_COPYRIGHT not in", values, "cashCopyright");
            return (Criteria) this;
        }

        public Criteria andCashCopyrightBetween(Double value1, Double value2) {
            addCriterion("CASH_COPYRIGHT between", value1, value2, "cashCopyright");
            return (Criteria) this;
        }

        public Criteria andCashCopyrightNotBetween(Double value1, Double value2) {
            addCriterion("CASH_COPYRIGHT not between", value1, value2, "cashCopyright");
            return (Criteria) this;
        }

        public Criteria andCashPublishIsNull() {
            addCriterion("CASH_PUBLISH is null");
            return (Criteria) this;
        }

        public Criteria andCashPublishIsNotNull() {
            addCriterion("CASH_PUBLISH is not null");
            return (Criteria) this;
        }

        public Criteria andCashPublishEqualTo(Double value) {
            addCriterion("CASH_PUBLISH =", value, "cashPublish");
            return (Criteria) this;
        }

        public Criteria andCashPublishNotEqualTo(Double value) {
            addCriterion("CASH_PUBLISH <>", value, "cashPublish");
            return (Criteria) this;
        }

        public Criteria andCashPublishGreaterThan(Double value) {
            addCriterion("CASH_PUBLISH >", value, "cashPublish");
            return (Criteria) this;
        }

        public Criteria andCashPublishGreaterThanOrEqualTo(Double value) {
            addCriterion("CASH_PUBLISH >=", value, "cashPublish");
            return (Criteria) this;
        }

        public Criteria andCashPublishLessThan(Double value) {
            addCriterion("CASH_PUBLISH <", value, "cashPublish");
            return (Criteria) this;
        }

        public Criteria andCashPublishLessThanOrEqualTo(Double value) {
            addCriterion("CASH_PUBLISH <=", value, "cashPublish");
            return (Criteria) this;
        }

        public Criteria andCashPublishIn(List<Double> values) {
            addCriterion("CASH_PUBLISH in", values, "cashPublish");
            return (Criteria) this;
        }

        public Criteria andCashPublishNotIn(List<Double> values) {
            addCriterion("CASH_PUBLISH not in", values, "cashPublish");
            return (Criteria) this;
        }

        public Criteria andCashPublishBetween(Double value1, Double value2) {
            addCriterion("CASH_PUBLISH between", value1, value2, "cashPublish");
            return (Criteria) this;
        }

        public Criteria andCashPublishNotBetween(Double value1, Double value2) {
            addCriterion("CASH_PUBLISH not between", value1, value2, "cashPublish");
            return (Criteria) this;
        }

        public Criteria andDateCreateIsNull() {
            addCriterion("DATE_CREATE is null");
            return (Criteria) this;
        }

        public Criteria andDateCreateIsNotNull() {
            addCriterion("DATE_CREATE is not null");
            return (Criteria) this;
        }

        public Criteria andDateCreateEqualTo(Date value) {
            addCriterion("DATE_CREATE =", value, "dateCreate");
            return (Criteria) this;
        }

        public Criteria andDateCreateNotEqualTo(Date value) {
            addCriterion("DATE_CREATE <>", value, "dateCreate");
            return (Criteria) this;
        }

        public Criteria andDateCreateGreaterThan(Date value) {
            addCriterion("DATE_CREATE >", value, "dateCreate");
            return (Criteria) this;
        }

        public Criteria andDateCreateGreaterThanOrEqualTo(Date value) {
            addCriterion("DATE_CREATE >=", value, "dateCreate");
            return (Criteria) this;
        }

        public Criteria andDateCreateLessThan(Date value) {
            addCriterion("DATE_CREATE <", value, "dateCreate");
            return (Criteria) this;
        }

        public Criteria andDateCreateLessThanOrEqualTo(Date value) {
            addCriterion("DATE_CREATE <=", value, "dateCreate");
            return (Criteria) this;
        }

        public Criteria andDateCreateIn(List<Date> values) {
            addCriterion("DATE_CREATE in", values, "dateCreate");
            return (Criteria) this;
        }

        public Criteria andDateCreateNotIn(List<Date> values) {
            addCriterion("DATE_CREATE not in", values, "dateCreate");
            return (Criteria) this;
        }

        public Criteria andDateCreateBetween(Date value1, Date value2) {
            addCriterion("DATE_CREATE between", value1, value2, "dateCreate");
            return (Criteria) this;
        }

        public Criteria andDateCreateNotBetween(Date value1, Date value2) {
            addCriterion("DATE_CREATE not between", value1, value2, "dateCreate");
            return (Criteria) this;
        }

        public Criteria andDateModifyIsNull() {
            addCriterion("DATE_MODIFY is null");
            return (Criteria) this;
        }

        public Criteria andDateModifyIsNotNull() {
            addCriterion("DATE_MODIFY is not null");
            return (Criteria) this;
        }

        public Criteria andDateModifyEqualTo(Date value) {
            addCriterion("DATE_MODIFY =", value, "dateModify");
            return (Criteria) this;
        }

        public Criteria andDateModifyNotEqualTo(Date value) {
            addCriterion("DATE_MODIFY <>", value, "dateModify");
            return (Criteria) this;
        }

        public Criteria andDateModifyGreaterThan(Date value) {
            addCriterion("DATE_MODIFY >", value, "dateModify");
            return (Criteria) this;
        }

        public Criteria andDateModifyGreaterThanOrEqualTo(Date value) {
            addCriterion("DATE_MODIFY >=", value, "dateModify");
            return (Criteria) this;
        }

        public Criteria andDateModifyLessThan(Date value) {
            addCriterion("DATE_MODIFY <", value, "dateModify");
            return (Criteria) this;
        }

        public Criteria andDateModifyLessThanOrEqualTo(Date value) {
            addCriterion("DATE_MODIFY <=", value, "dateModify");
            return (Criteria) this;
        }

        public Criteria andDateModifyIn(List<Date> values) {
            addCriterion("DATE_MODIFY in", values, "dateModify");
            return (Criteria) this;
        }

        public Criteria andDateModifyNotIn(List<Date> values) {
            addCriterion("DATE_MODIFY not in", values, "dateModify");
            return (Criteria) this;
        }

        public Criteria andDateModifyBetween(Date value1, Date value2) {
            addCriterion("DATE_MODIFY between", value1, value2, "dateModify");
            return (Criteria) this;
        }

        public Criteria andDateModifyNotBetween(Date value1, Date value2) {
            addCriterion("DATE_MODIFY not between", value1, value2, "dateModify");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table yunear_order
     *
     * @mbggenerated do_not_delete_during_merge Sat Oct 15 10:03:07 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table yunear_order
     *
     * @mbggenerated Sat Oct 15 10:03:07 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}