package com.kakasure.bqf.dao.model;

public class Role {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.ROLE_ID
     *
     * @mbggenerated Tue Oct 11 15:46:15 CST 2016
     */
    private String roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.ROLE_NAME
     *
     * @mbggenerated Tue Oct 11 15:46:15 CST 2016
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.RIGHTS
     *
     * @mbggenerated Tue Oct 11 15:46:15 CST 2016
     */
    private String rights;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.PARENT_ID
     *
     * @mbggenerated Tue Oct 11 15:46:15 CST 2016
     */
    private String parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.ADD_QX
     *
     * @mbggenerated Tue Oct 11 15:46:15 CST 2016
     */
    private String addQx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.DEL_QX
     *
     * @mbggenerated Tue Oct 11 15:46:15 CST 2016
     */
    private String delQx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.EDIT_QX
     *
     * @mbggenerated Tue Oct 11 15:46:15 CST 2016
     */
    private String editQx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.CHA_QX
     *
     * @mbggenerated Tue Oct 11 15:46:15 CST 2016
     */
    private String chaQx;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_role.QX_ID
     *
     * @mbggenerated Tue Oct 11 15:46:15 CST 2016
     */
    private String qxId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.ROLE_ID
     *
     * @return the value of sys_role.ROLE_ID
     *
     * @mbggenerated Tue Oct 11 15:46:15 CST 2016
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.ROLE_ID
     *
     * @param roleId the value for sys_role.ROLE_ID
     *
     * @mbggenerated Tue Oct 11 15:46:15 CST 2016
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.ROLE_NAME
     *
     * @return the value of sys_role.ROLE_NAME
     *
     * @mbggenerated Tue Oct 11 15:46:15 CST 2016
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.ROLE_NAME
     *
     * @param roleName the value for sys_role.ROLE_NAME
     *
     * @mbggenerated Tue Oct 11 15:46:15 CST 2016
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.RIGHTS
     *
     * @return the value of sys_role.RIGHTS
     *
     * @mbggenerated Tue Oct 11 15:46:15 CST 2016
     */
    public String getRights() {
        return rights;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.RIGHTS
     *
     * @param rights the value for sys_role.RIGHTS
     *
     * @mbggenerated Tue Oct 11 15:46:15 CST 2016
     */
    public void setRights(String rights) {
        this.rights = rights;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.PARENT_ID
     *
     * @return the value of sys_role.PARENT_ID
     *
     * @mbggenerated Tue Oct 11 15:46:15 CST 2016
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.PARENT_ID
     *
     * @param parentId the value for sys_role.PARENT_ID
     *
     * @mbggenerated Tue Oct 11 15:46:15 CST 2016
     */
    public void setParentId(String parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.ADD_QX
     *
     * @return the value of sys_role.ADD_QX
     *
     * @mbggenerated Tue Oct 11 15:46:15 CST 2016
     */
    public String getAddQx() {
        return addQx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.ADD_QX
     *
     * @param addQx the value for sys_role.ADD_QX
     *
     * @mbggenerated Tue Oct 11 15:46:15 CST 2016
     */
    public void setAddQx(String addQx) {
        this.addQx = addQx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.DEL_QX
     *
     * @return the value of sys_role.DEL_QX
     *
     * @mbggenerated Tue Oct 11 15:46:15 CST 2016
     */
    public String getDelQx() {
        return delQx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.DEL_QX
     *
     * @param delQx the value for sys_role.DEL_QX
     *
     * @mbggenerated Tue Oct 11 15:46:15 CST 2016
     */
    public void setDelQx(String delQx) {
        this.delQx = delQx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.EDIT_QX
     *
     * @return the value of sys_role.EDIT_QX
     *
     * @mbggenerated Tue Oct 11 15:46:15 CST 2016
     */
    public String getEditQx() {
        return editQx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.EDIT_QX
     *
     * @param editQx the value for sys_role.EDIT_QX
     *
     * @mbggenerated Tue Oct 11 15:46:15 CST 2016
     */
    public void setEditQx(String editQx) {
        this.editQx = editQx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.CHA_QX
     *
     * @return the value of sys_role.CHA_QX
     *
     * @mbggenerated Tue Oct 11 15:46:15 CST 2016
     */
    public String getChaQx() {
        return chaQx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.CHA_QX
     *
     * @param chaQx the value for sys_role.CHA_QX
     *
     * @mbggenerated Tue Oct 11 15:46:15 CST 2016
     */
    public void setChaQx(String chaQx) {
        this.chaQx = chaQx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_role.QX_ID
     *
     * @return the value of sys_role.QX_ID
     *
     * @mbggenerated Tue Oct 11 15:46:15 CST 2016
     */
    public String getQxId() {
        return qxId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_role.QX_ID
     *
     * @param qxId the value for sys_role.QX_ID
     *
     * @mbggenerated Tue Oct 11 15:46:15 CST 2016
     */
    public void setQxId(String qxId) {
        this.qxId = qxId;
    }
}