package com.kakasure.bqf.dao.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SysConfigExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_config
     *
     * @mbggenerated Wed Nov 09 11:40:45 GMT+08:00 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_config
     *
     * @mbggenerated Wed Nov 09 11:40:45 GMT+08:00 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_config
     *
     * @mbggenerated Wed Nov 09 11:40:45 GMT+08:00 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config
     *
     * @mbggenerated Wed Nov 09 11:40:45 GMT+08:00 2016
     */
    public SysConfigExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config
     *
     * @mbggenerated Wed Nov 09 11:40:45 GMT+08:00 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config
     *
     * @mbggenerated Wed Nov 09 11:40:45 GMT+08:00 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config
     *
     * @mbggenerated Wed Nov 09 11:40:45 GMT+08:00 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config
     *
     * @mbggenerated Wed Nov 09 11:40:45 GMT+08:00 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config
     *
     * @mbggenerated Wed Nov 09 11:40:45 GMT+08:00 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config
     *
     * @mbggenerated Wed Nov 09 11:40:45 GMT+08:00 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config
     *
     * @mbggenerated Wed Nov 09 11:40:45 GMT+08:00 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config
     *
     * @mbggenerated Wed Nov 09 11:40:45 GMT+08:00 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config
     *
     * @mbggenerated Wed Nov 09 11:40:45 GMT+08:00 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_config
     *
     * @mbggenerated Wed Nov 09 11:40:45 GMT+08:00 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_config
     *
     * @mbggenerated Wed Nov 09 11:40:45 GMT+08:00 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andKksKeyIsNull() {
            addCriterion("kks_key is null");
            return (Criteria) this;
        }

        public Criteria andKksKeyIsNotNull() {
            addCriterion("kks_key is not null");
            return (Criteria) this;
        }

        public Criteria andKksKeyEqualTo(String value) {
            addCriterion("kks_key =", value, "kksKey");
            return (Criteria) this;
        }

        public Criteria andKksKeyNotEqualTo(String value) {
            addCriterion("kks_key <>", value, "kksKey");
            return (Criteria) this;
        }

        public Criteria andKksKeyGreaterThan(String value) {
            addCriterion("kks_key >", value, "kksKey");
            return (Criteria) this;
        }

        public Criteria andKksKeyGreaterThanOrEqualTo(String value) {
            addCriterion("kks_key >=", value, "kksKey");
            return (Criteria) this;
        }

        public Criteria andKksKeyLessThan(String value) {
            addCriterion("kks_key <", value, "kksKey");
            return (Criteria) this;
        }

        public Criteria andKksKeyLessThanOrEqualTo(String value) {
            addCriterion("kks_key <=", value, "kksKey");
            return (Criteria) this;
        }

        public Criteria andKksKeyLike(String value) {
            addCriterion("kks_key like", value, "kksKey");
            return (Criteria) this;
        }

        public Criteria andKksKeyNotLike(String value) {
            addCriterion("kks_key not like", value, "kksKey");
            return (Criteria) this;
        }

        public Criteria andKksKeyIn(List<String> values) {
            addCriterion("kks_key in", values, "kksKey");
            return (Criteria) this;
        }

        public Criteria andKksKeyNotIn(List<String> values) {
            addCriterion("kks_key not in", values, "kksKey");
            return (Criteria) this;
        }

        public Criteria andKksKeyBetween(String value1, String value2) {
            addCriterion("kks_key between", value1, value2, "kksKey");
            return (Criteria) this;
        }

        public Criteria andKksKeyNotBetween(String value1, String value2) {
            addCriterion("kks_key not between", value1, value2, "kksKey");
            return (Criteria) this;
        }

        public Criteria andKksValueIsNull() {
            addCriterion("kks_value is null");
            return (Criteria) this;
        }

        public Criteria andKksValueIsNotNull() {
            addCriterion("kks_value is not null");
            return (Criteria) this;
        }

        public Criteria andKksValueEqualTo(String value) {
            addCriterion("kks_value =", value, "kksValue");
            return (Criteria) this;
        }

        public Criteria andKksValueNotEqualTo(String value) {
            addCriterion("kks_value <>", value, "kksValue");
            return (Criteria) this;
        }

        public Criteria andKksValueGreaterThan(String value) {
            addCriterion("kks_value >", value, "kksValue");
            return (Criteria) this;
        }

        public Criteria andKksValueGreaterThanOrEqualTo(String value) {
            addCriterion("kks_value >=", value, "kksValue");
            return (Criteria) this;
        }

        public Criteria andKksValueLessThan(String value) {
            addCriterion("kks_value <", value, "kksValue");
            return (Criteria) this;
        }

        public Criteria andKksValueLessThanOrEqualTo(String value) {
            addCriterion("kks_value <=", value, "kksValue");
            return (Criteria) this;
        }

        public Criteria andKksValueLike(String value) {
            addCriterion("kks_value like", value, "kksValue");
            return (Criteria) this;
        }

        public Criteria andKksValueNotLike(String value) {
            addCriterion("kks_value not like", value, "kksValue");
            return (Criteria) this;
        }

        public Criteria andKksValueIn(List<String> values) {
            addCriterion("kks_value in", values, "kksValue");
            return (Criteria) this;
        }

        public Criteria andKksValueNotIn(List<String> values) {
            addCriterion("kks_value not in", values, "kksValue");
            return (Criteria) this;
        }

        public Criteria andKksValueBetween(String value1, String value2) {
            addCriterion("kks_value between", value1, value2, "kksValue");
            return (Criteria) this;
        }

        public Criteria andKksValueNotBetween(String value1, String value2) {
            addCriterion("kks_value not between", value1, value2, "kksValue");
            return (Criteria) this;
        }

        public Criteria andCfgTypeIsNull() {
            addCriterion("cfg_type is null");
            return (Criteria) this;
        }

        public Criteria andCfgTypeIsNotNull() {
            addCriterion("cfg_type is not null");
            return (Criteria) this;
        }

        public Criteria andCfgTypeEqualTo(String value) {
            addCriterion("cfg_type =", value, "cfgType");
            return (Criteria) this;
        }

        public Criteria andCfgTypeNotEqualTo(String value) {
            addCriterion("cfg_type <>", value, "cfgType");
            return (Criteria) this;
        }

        public Criteria andCfgTypeGreaterThan(String value) {
            addCriterion("cfg_type >", value, "cfgType");
            return (Criteria) this;
        }

        public Criteria andCfgTypeGreaterThanOrEqualTo(String value) {
            addCriterion("cfg_type >=", value, "cfgType");
            return (Criteria) this;
        }

        public Criteria andCfgTypeLessThan(String value) {
            addCriterion("cfg_type <", value, "cfgType");
            return (Criteria) this;
        }

        public Criteria andCfgTypeLessThanOrEqualTo(String value) {
            addCriterion("cfg_type <=", value, "cfgType");
            return (Criteria) this;
        }

        public Criteria andCfgTypeLike(String value) {
            addCriterion("cfg_type like", value, "cfgType");
            return (Criteria) this;
        }

        public Criteria andCfgTypeNotLike(String value) {
            addCriterion("cfg_type not like", value, "cfgType");
            return (Criteria) this;
        }

        public Criteria andCfgTypeIn(List<String> values) {
            addCriterion("cfg_type in", values, "cfgType");
            return (Criteria) this;
        }

        public Criteria andCfgTypeNotIn(List<String> values) {
            addCriterion("cfg_type not in", values, "cfgType");
            return (Criteria) this;
        }

        public Criteria andCfgTypeBetween(String value1, String value2) {
            addCriterion("cfg_type between", value1, value2, "cfgType");
            return (Criteria) this;
        }

        public Criteria andCfgTypeNotBetween(String value1, String value2) {
            addCriterion("cfg_type not between", value1, value2, "cfgType");
            return (Criteria) this;
        }

        public Criteria andCfgDescIsNull() {
            addCriterion("cfg_desc is null");
            return (Criteria) this;
        }

        public Criteria andCfgDescIsNotNull() {
            addCriterion("cfg_desc is not null");
            return (Criteria) this;
        }

        public Criteria andCfgDescEqualTo(String value) {
            addCriterion("cfg_desc =", value, "cfgDesc");
            return (Criteria) this;
        }

        public Criteria andCfgDescNotEqualTo(String value) {
            addCriterion("cfg_desc <>", value, "cfgDesc");
            return (Criteria) this;
        }

        public Criteria andCfgDescGreaterThan(String value) {
            addCriterion("cfg_desc >", value, "cfgDesc");
            return (Criteria) this;
        }

        public Criteria andCfgDescGreaterThanOrEqualTo(String value) {
            addCriterion("cfg_desc >=", value, "cfgDesc");
            return (Criteria) this;
        }

        public Criteria andCfgDescLessThan(String value) {
            addCriterion("cfg_desc <", value, "cfgDesc");
            return (Criteria) this;
        }

        public Criteria andCfgDescLessThanOrEqualTo(String value) {
            addCriterion("cfg_desc <=", value, "cfgDesc");
            return (Criteria) this;
        }

        public Criteria andCfgDescLike(String value) {
            addCriterion("cfg_desc like", value, "cfgDesc");
            return (Criteria) this;
        }

        public Criteria andCfgDescNotLike(String value) {
            addCriterion("cfg_desc not like", value, "cfgDesc");
            return (Criteria) this;
        }

        public Criteria andCfgDescIn(List<String> values) {
            addCriterion("cfg_desc in", values, "cfgDesc");
            return (Criteria) this;
        }

        public Criteria andCfgDescNotIn(List<String> values) {
            addCriterion("cfg_desc not in", values, "cfgDesc");
            return (Criteria) this;
        }

        public Criteria andCfgDescBetween(String value1, String value2) {
            addCriterion("cfg_desc between", value1, value2, "cfgDesc");
            return (Criteria) this;
        }

        public Criteria andCfgDescNotBetween(String value1, String value2) {
            addCriterion("cfg_desc not between", value1, value2, "cfgDesc");
            return (Criteria) this;
        }

        public Criteria andGmtCreatedIsNull() {
            addCriterion("gmt_created is null");
            return (Criteria) this;
        }

        public Criteria andGmtCreatedIsNotNull() {
            addCriterion("gmt_created is not null");
            return (Criteria) this;
        }

        public Criteria andGmtCreatedEqualTo(Date value) {
            addCriterion("gmt_created =", value, "gmtCreated");
            return (Criteria) this;
        }

        public Criteria andGmtCreatedNotEqualTo(Date value) {
            addCriterion("gmt_created <>", value, "gmtCreated");
            return (Criteria) this;
        }

        public Criteria andGmtCreatedGreaterThan(Date value) {
            addCriterion("gmt_created >", value, "gmtCreated");
            return (Criteria) this;
        }

        public Criteria andGmtCreatedGreaterThanOrEqualTo(Date value) {
            addCriterion("gmt_created >=", value, "gmtCreated");
            return (Criteria) this;
        }

        public Criteria andGmtCreatedLessThan(Date value) {
            addCriterion("gmt_created <", value, "gmtCreated");
            return (Criteria) this;
        }

        public Criteria andGmtCreatedLessThanOrEqualTo(Date value) {
            addCriterion("gmt_created <=", value, "gmtCreated");
            return (Criteria) this;
        }

        public Criteria andGmtCreatedIn(List<Date> values) {
            addCriterion("gmt_created in", values, "gmtCreated");
            return (Criteria) this;
        }

        public Criteria andGmtCreatedNotIn(List<Date> values) {
            addCriterion("gmt_created not in", values, "gmtCreated");
            return (Criteria) this;
        }

        public Criteria andGmtCreatedBetween(Date value1, Date value2) {
            addCriterion("gmt_created between", value1, value2, "gmtCreated");
            return (Criteria) this;
        }

        public Criteria andGmtCreatedNotBetween(Date value1, Date value2) {
            addCriterion("gmt_created not between", value1, value2, "gmtCreated");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIsNull() {
            addCriterion("gmt_modified is null");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIsNotNull() {
            addCriterion("gmt_modified is not null");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedEqualTo(Date value) {
            addCriterion("gmt_modified =", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotEqualTo(Date value) {
            addCriterion("gmt_modified <>", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedGreaterThan(Date value) {
            addCriterion("gmt_modified >", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedGreaterThanOrEqualTo(Date value) {
            addCriterion("gmt_modified >=", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedLessThan(Date value) {
            addCriterion("gmt_modified <", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedLessThanOrEqualTo(Date value) {
            addCriterion("gmt_modified <=", value, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedIn(List<Date> values) {
            addCriterion("gmt_modified in", values, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotIn(List<Date> values) {
            addCriterion("gmt_modified not in", values, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedBetween(Date value1, Date value2) {
            addCriterion("gmt_modified between", value1, value2, "gmtModified");
            return (Criteria) this;
        }

        public Criteria andGmtModifiedNotBetween(Date value1, Date value2) {
            addCriterion("gmt_modified not between", value1, value2, "gmtModified");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_config
     *
     * @mbggenerated do_not_delete_during_merge Wed Nov 09 11:40:45 GMT+08:00 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sys_config
     *
     * @mbggenerated Wed Nov 09 11:40:45 GMT+08:00 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}