package com.kakasure.bqf.dao.model;

import java.util.Date;

public class SysConfig {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config.kks_key
     *
     * @mbggenerated Wed Nov 09 11:40:45 GMT+08:00 2016
     */
    private String kksKey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config.kks_value
     *
     * @mbggenerated Wed Nov 09 11:40:45 GMT+08:00 2016
     */
    private String kksValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config.cfg_type
     *
     * @mbggenerated Wed Nov 09 11:40:45 GMT+08:00 2016
     */
    private String cfgType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config.cfg_desc
     *
     * @mbggenerated Wed Nov 09 11:40:45 GMT+08:00 2016
     */
    private String cfgDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config.gmt_created
     *
     * @mbggenerated Wed Nov 09 11:40:45 GMT+08:00 2016
     */
    private Date gmtCreated;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_config.gmt_modified
     *
     * @mbggenerated Wed Nov 09 11:40:45 GMT+08:00 2016
     */
    private Date gmtModified;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config.kks_key
     *
     * @return the value of sys_config.kks_key
     *
     * @mbggenerated Wed Nov 09 11:40:45 GMT+08:00 2016
     */
    public String getKksKey() {
        return kksKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config.kks_key
     *
     * @param kksKey the value for sys_config.kks_key
     *
     * @mbggenerated Wed Nov 09 11:40:45 GMT+08:00 2016
     */
    public void setKksKey(String kksKey) {
        this.kksKey = kksKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config.kks_value
     *
     * @return the value of sys_config.kks_value
     *
     * @mbggenerated Wed Nov 09 11:40:45 GMT+08:00 2016
     */
    public String getKksValue() {
        return kksValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config.kks_value
     *
     * @param kksValue the value for sys_config.kks_value
     *
     * @mbggenerated Wed Nov 09 11:40:45 GMT+08:00 2016
     */
    public void setKksValue(String kksValue) {
        this.kksValue = kksValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config.cfg_type
     *
     * @return the value of sys_config.cfg_type
     *
     * @mbggenerated Wed Nov 09 11:40:45 GMT+08:00 2016
     */
    public String getCfgType() {
        return cfgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config.cfg_type
     *
     * @param cfgType the value for sys_config.cfg_type
     *
     * @mbggenerated Wed Nov 09 11:40:45 GMT+08:00 2016
     */
    public void setCfgType(String cfgType) {
        this.cfgType = cfgType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config.cfg_desc
     *
     * @return the value of sys_config.cfg_desc
     *
     * @mbggenerated Wed Nov 09 11:40:45 GMT+08:00 2016
     */
    public String getCfgDesc() {
        return cfgDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config.cfg_desc
     *
     * @param cfgDesc the value for sys_config.cfg_desc
     *
     * @mbggenerated Wed Nov 09 11:40:45 GMT+08:00 2016
     */
    public void setCfgDesc(String cfgDesc) {
        this.cfgDesc = cfgDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config.gmt_created
     *
     * @return the value of sys_config.gmt_created
     *
     * @mbggenerated Wed Nov 09 11:40:45 GMT+08:00 2016
     */
    public Date getGmtCreated() {
        return gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config.gmt_created
     *
     * @param gmtCreated the value for sys_config.gmt_created
     *
     * @mbggenerated Wed Nov 09 11:40:45 GMT+08:00 2016
     */
    public void setGmtCreated(Date gmtCreated) {
        this.gmtCreated = gmtCreated;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_config.gmt_modified
     *
     * @return the value of sys_config.gmt_modified
     *
     * @mbggenerated Wed Nov 09 11:40:45 GMT+08:00 2016
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_config.gmt_modified
     *
     * @param gmtModified the value for sys_config.gmt_modified
     *
     * @mbggenerated Wed Nov 09 11:40:45 GMT+08:00 2016
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }
}