package com.kakasure.bqf.dao.model;

public class ThemeProduct {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunear_theme_product.THEME_ID
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    private String themeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunear_theme_product.PRODUCT_ID
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    private String productId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunear_theme_product.THEME_ID
     *
     * @return the value of yunear_theme_product.THEME_ID
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    public String getThemeId() {
        return themeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunear_theme_product.THEME_ID
     *
     * @param themeId the value for yunear_theme_product.THEME_ID
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    public void setThemeId(String themeId) {
        this.themeId = themeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunear_theme_product.PRODUCT_ID
     *
     * @return the value of yunear_theme_product.PRODUCT_ID
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunear_theme_product.PRODUCT_ID
     *
     * @param productId the value for yunear_theme_product.PRODUCT_ID
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    public void setProductId(String productId) {
        this.productId = productId;
    }
}