package com.kakasure.bqf.dao.model;

import java.util.Date;

public class Theme {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunear_theme.THEME_ID
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    private String themeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunear_theme.USER_ID
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunear_theme.THEME_NAME
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    private String themeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunear_theme.IS_DELETE
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    private String isDelete;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunear_theme.DATE_CREATE
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    private Date dateCreate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunear_theme.DATE_MODIFY
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    private Date dateModify;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunear_theme.THEME_ID
     *
     * @return the value of yunear_theme.THEME_ID
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    public String getThemeId() {
        return themeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunear_theme.THEME_ID
     *
     * @param themeId the value for yunear_theme.THEME_ID
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    public void setThemeId(String themeId) {
        this.themeId = themeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunear_theme.USER_ID
     *
     * @return the value of yunear_theme.USER_ID
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunear_theme.USER_ID
     *
     * @param userId the value for yunear_theme.USER_ID
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunear_theme.THEME_NAME
     *
     * @return the value of yunear_theme.THEME_NAME
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    public String getThemeName() {
        return themeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunear_theme.THEME_NAME
     *
     * @param themeName the value for yunear_theme.THEME_NAME
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    public void setThemeName(String themeName) {
        this.themeName = themeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunear_theme.IS_DELETE
     *
     * @return the value of yunear_theme.IS_DELETE
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    public String getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunear_theme.IS_DELETE
     *
     * @param isDelete the value for yunear_theme.IS_DELETE
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    public void setIsDelete(String isDelete) {
        this.isDelete = isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunear_theme.DATE_CREATE
     *
     * @return the value of yunear_theme.DATE_CREATE
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    public Date getDateCreate() {
        return dateCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunear_theme.DATE_CREATE
     *
     * @param dateCreate the value for yunear_theme.DATE_CREATE
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    public void setDateCreate(Date dateCreate) {
        this.dateCreate = dateCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunear_theme.DATE_MODIFY
     *
     * @return the value of yunear_theme.DATE_MODIFY
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    public Date getDateModify() {
        return dateModify;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunear_theme.DATE_MODIFY
     *
     * @param dateModify the value for yunear_theme.DATE_MODIFY
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    public void setDateModify(Date dateModify) {
        this.dateModify = dateModify;
    }
}