package com.kakasure.bqf.dao.model;

public class ThemeAnnounce {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunear_theme_announce.THEME_ID
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    private String themeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunear_theme_announce.ANNOUNCEMULTI_ID
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    private String announcemultiId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunear_theme_announce.THEME_ID
     *
     * @return the value of yunear_theme_announce.THEME_ID
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    public String getThemeId() {
        return themeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunear_theme_announce.THEME_ID
     *
     * @param themeId the value for yunear_theme_announce.THEME_ID
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    public void setThemeId(String themeId) {
        this.themeId = themeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunear_theme_announce.ANNOUNCEMULTI_ID
     *
     * @return the value of yunear_theme_announce.ANNOUNCEMULTI_ID
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    public String getAnnouncemultiId() {
        return announcemultiId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunear_theme_announce.ANNOUNCEMULTI_ID
     *
     * @param announcemultiId the value for yunear_theme_announce.ANNOUNCEMULTI_ID
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    public void setAnnouncemultiId(String announcemultiId) {
        this.announcemultiId = announcemultiId;
    }
}