package com.kakasure.bqf.dao.model;

import java.util.Date;

public class Userplus {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunear_userplus.USER_ID
     *
     * @mbggenerated Tue Nov 29 13:59:55 CST 2016
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunear_userplus.USER_NAME
     *
     * @mbggenerated Tue Nov 29 13:59:55 CST 2016
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunear_userplus.ALIPAY_ACCOUNT
     *
     * @mbggenerated Tue Nov 29 13:59:55 CST 2016
     */
    private String alipayAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunear_userplus.ALIPAYNAME
     *
     * @mbggenerated Tue Nov 29 13:59:55 CST 2016
     */
    private String alipayname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunear_userplus.BANK_ACCOUNT
     *
     * @mbggenerated Tue Nov 29 13:59:55 CST 2016
     */
    private String bankAccount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunear_userplus.BANK_TYPE
     *
     * @mbggenerated Tue Nov 29 13:59:55 CST 2016
     */
    private String bankType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunear_userplus.BANK_NAME
     *
     * @mbggenerated Tue Nov 29 13:59:55 CST 2016
     */
    private String bankName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunear_userplus.BANK_LOCATION
     *
     * @mbggenerated Tue Nov 29 13:59:55 CST 2016
     */
    private String bankLocation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunear_userplus.BANK_USER_NAME
     *
     * @mbggenerated Tue Nov 29 13:59:55 CST 2016
     */
    private String bankUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunear_userplus.FORCOMPNY
     *
     * @mbggenerated Tue Nov 29 13:59:55 CST 2016
     */
    private String forcompny;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunear_userplus.CREATE_TIME
     *
     * @mbggenerated Tue Nov 29 13:59:55 CST 2016
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunear_userplus.UPDATE_TIME
     *
     * @mbggenerated Tue Nov 29 13:59:55 CST 2016
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunear_userplus.PHONE
     *
     * @mbggenerated Tue Nov 29 13:59:55 CST 2016
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column yunear_userplus.IS_DELETE
     *
     * @mbggenerated Tue Nov 29 13:59:55 CST 2016
     */
    private String isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunear_userplus.USER_ID
     *
     * @return the value of yunear_userplus.USER_ID
     *
     * @mbggenerated Tue Nov 29 13:59:55 CST 2016
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunear_userplus.USER_ID
     *
     * @param userId the value for yunear_userplus.USER_ID
     *
     * @mbggenerated Tue Nov 29 13:59:55 CST 2016
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunear_userplus.USER_NAME
     *
     * @return the value of yunear_userplus.USER_NAME
     *
     * @mbggenerated Tue Nov 29 13:59:55 CST 2016
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunear_userplus.USER_NAME
     *
     * @param userName the value for yunear_userplus.USER_NAME
     *
     * @mbggenerated Tue Nov 29 13:59:55 CST 2016
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunear_userplus.ALIPAY_ACCOUNT
     *
     * @return the value of yunear_userplus.ALIPAY_ACCOUNT
     *
     * @mbggenerated Tue Nov 29 13:59:55 CST 2016
     */
    public String getAlipayAccount() {
        return alipayAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunear_userplus.ALIPAY_ACCOUNT
     *
     * @param alipayAccount the value for yunear_userplus.ALIPAY_ACCOUNT
     *
     * @mbggenerated Tue Nov 29 13:59:55 CST 2016
     */
    public void setAlipayAccount(String alipayAccount) {
        this.alipayAccount = alipayAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunear_userplus.ALIPAYNAME
     *
     * @return the value of yunear_userplus.ALIPAYNAME
     *
     * @mbggenerated Tue Nov 29 13:59:55 CST 2016
     */
    public String getAlipayname() {
        return alipayname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunear_userplus.ALIPAYNAME
     *
     * @param alipayname the value for yunear_userplus.ALIPAYNAME
     *
     * @mbggenerated Tue Nov 29 13:59:55 CST 2016
     */
    public void setAlipayname(String alipayname) {
        this.alipayname = alipayname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunear_userplus.BANK_ACCOUNT
     *
     * @return the value of yunear_userplus.BANK_ACCOUNT
     *
     * @mbggenerated Tue Nov 29 13:59:55 CST 2016
     */
    public String getBankAccount() {
        return bankAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunear_userplus.BANK_ACCOUNT
     *
     * @param bankAccount the value for yunear_userplus.BANK_ACCOUNT
     *
     * @mbggenerated Tue Nov 29 13:59:55 CST 2016
     */
    public void setBankAccount(String bankAccount) {
        this.bankAccount = bankAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunear_userplus.BANK_TYPE
     *
     * @return the value of yunear_userplus.BANK_TYPE
     *
     * @mbggenerated Tue Nov 29 13:59:55 CST 2016
     */
    public String getBankType() {
        return bankType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunear_userplus.BANK_TYPE
     *
     * @param bankType the value for yunear_userplus.BANK_TYPE
     *
     * @mbggenerated Tue Nov 29 13:59:55 CST 2016
     */
    public void setBankType(String bankType) {
        this.bankType = bankType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunear_userplus.BANK_NAME
     *
     * @return the value of yunear_userplus.BANK_NAME
     *
     * @mbggenerated Tue Nov 29 13:59:55 CST 2016
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunear_userplus.BANK_NAME
     *
     * @param bankName the value for yunear_userplus.BANK_NAME
     *
     * @mbggenerated Tue Nov 29 13:59:55 CST 2016
     */
    public void setBankName(String bankName) {
        this.bankName = bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunear_userplus.BANK_LOCATION
     *
     * @return the value of yunear_userplus.BANK_LOCATION
     *
     * @mbggenerated Tue Nov 29 13:59:55 CST 2016
     */
    public String getBankLocation() {
        return bankLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunear_userplus.BANK_LOCATION
     *
     * @param bankLocation the value for yunear_userplus.BANK_LOCATION
     *
     * @mbggenerated Tue Nov 29 13:59:55 CST 2016
     */
    public void setBankLocation(String bankLocation) {
        this.bankLocation = bankLocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunear_userplus.BANK_USER_NAME
     *
     * @return the value of yunear_userplus.BANK_USER_NAME
     *
     * @mbggenerated Tue Nov 29 13:59:55 CST 2016
     */
    public String getBankUserName() {
        return bankUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunear_userplus.BANK_USER_NAME
     *
     * @param bankUserName the value for yunear_userplus.BANK_USER_NAME
     *
     * @mbggenerated Tue Nov 29 13:59:55 CST 2016
     */
    public void setBankUserName(String bankUserName) {
        this.bankUserName = bankUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunear_userplus.FORCOMPNY
     *
     * @return the value of yunear_userplus.FORCOMPNY
     *
     * @mbggenerated Tue Nov 29 13:59:55 CST 2016
     */
    public String getForcompny() {
        return forcompny;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunear_userplus.FORCOMPNY
     *
     * @param forcompny the value for yunear_userplus.FORCOMPNY
     *
     * @mbggenerated Tue Nov 29 13:59:55 CST 2016
     */
    public void setForcompny(String forcompny) {
        this.forcompny = forcompny;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunear_userplus.CREATE_TIME
     *
     * @return the value of yunear_userplus.CREATE_TIME
     *
     * @mbggenerated Tue Nov 29 13:59:55 CST 2016
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunear_userplus.CREATE_TIME
     *
     * @param createTime the value for yunear_userplus.CREATE_TIME
     *
     * @mbggenerated Tue Nov 29 13:59:55 CST 2016
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunear_userplus.UPDATE_TIME
     *
     * @return the value of yunear_userplus.UPDATE_TIME
     *
     * @mbggenerated Tue Nov 29 13:59:55 CST 2016
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunear_userplus.UPDATE_TIME
     *
     * @param updateTime the value for yunear_userplus.UPDATE_TIME
     *
     * @mbggenerated Tue Nov 29 13:59:55 CST 2016
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunear_userplus.PHONE
     *
     * @return the value of yunear_userplus.PHONE
     *
     * @mbggenerated Tue Nov 29 13:59:55 CST 2016
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunear_userplus.PHONE
     *
     * @param phone the value for yunear_userplus.PHONE
     *
     * @mbggenerated Tue Nov 29 13:59:55 CST 2016
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column yunear_userplus.IS_DELETE
     *
     * @return the value of yunear_userplus.IS_DELETE
     *
     * @mbggenerated Tue Nov 29 13:59:55 CST 2016
     */
    public String getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column yunear_userplus.IS_DELETE
     *
     * @param isDelete the value for yunear_userplus.IS_DELETE
     *
     * @mbggenerated Tue Nov 29 13:59:55 CST 2016
     */
    public void setIsDelete(String isDelete) {
        this.isDelete = isDelete;
    }
}