package com.kakasure.bqf.dao.mapper;

import com.kakasure.bqf.dao.model.Copyrightmulti;
import com.kakasure.bqf.dao.model.CopyrightmultiExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CopyrightmultiMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunear_copyrightmulti
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    int countByExample(CopyrightmultiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunear_copyrightmulti
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    int deleteByExample(CopyrightmultiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunear_copyrightmulti
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    int deleteByPrimaryKey(String copyrightmultiId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunear_copyrightmulti
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    int insertSelective(Copyrightmulti record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunear_copyrightmulti
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    List<Copyrightmulti> selectByExample(CopyrightmultiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunear_copyrightmulti
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    Copyrightmulti selectByPrimaryKey(String copyrightmultiId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunear_copyrightmulti
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    int updateByExampleSelective(@Param("record") Copyrightmulti record, @Param("example") CopyrightmultiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunear_copyrightmulti
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    int updateByExample(@Param("record") Copyrightmulti record, @Param("example") CopyrightmultiExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunear_copyrightmulti
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    int updateByPrimaryKeySelective(Copyrightmulti record);
}