package com.kakasure.bqf.dao.mapper;

import com.kakasure.bqf.dao.model.Labels;
import com.kakasure.bqf.dao.model.LabelsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LabelsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunear_labels
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    int countByExample(LabelsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunear_labels
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    int deleteByExample(LabelsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunear_labels
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    int deleteByPrimaryKey(String labelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunear_labels
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    int insertSelective(Labels record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunear_labels
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    List<Labels> selectByExample(LabelsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunear_labels
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    Labels selectByPrimaryKey(String labelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunear_labels
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    int updateByExampleSelective(@Param("record") Labels record, @Param("example") LabelsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunear_labels
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    int updateByExample(@Param("record") Labels record, @Param("example") LabelsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunear_labels
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    int updateByPrimaryKeySelective(Labels record);
}