package com.kakasure.bqf.dao.mapper;

import com.kakasure.bqf.dao.model.LiveBalance;
import com.kakasure.bqf.dao.model.LiveBalanceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LiveBalanceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunear_live_balance
     *
     * @mbggenerated Wed Sep 28 15:34:21 CST 2016
     */
    int countByExample(LiveBalanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunear_live_balance
     *
     * @mbggenerated Wed Sep 28 15:34:21 CST 2016
     */
    int deleteByExample(LiveBalanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunear_live_balance
     *
     * @mbggenerated Wed Sep 28 15:34:21 CST 2016
     */
    int deleteByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunear_live_balance
     *
     * @mbggenerated Wed Sep 28 15:34:21 CST 2016
     */
    int insertSelective(LiveBalance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunear_live_balance
     *
     * @mbggenerated Wed Sep 28 15:34:21 CST 2016
     */
    List<LiveBalance> selectByExample(LiveBalanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunear_live_balance
     *
     * @mbggenerated Wed Sep 28 15:34:21 CST 2016
     */
    LiveBalance selectByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunear_live_balance
     *
     * @mbggenerated Wed Sep 28 15:34:21 CST 2016
     */
    int updateByExampleSelective(@Param("record") LiveBalance record, @Param("example") LiveBalanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunear_live_balance
     *
     * @mbggenerated Wed Sep 28 15:34:21 CST 2016
     */
    int updateByExample(@Param("record") LiveBalance record, @Param("example") LiveBalanceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunear_live_balance
     *
     * @mbggenerated Wed Sep 28 15:34:21 CST 2016
     */
    int updateByPrimaryKeySelective(LiveBalance record);
}