package com.kakasure.bqf.dao.mapper;

import com.kakasure.bqf.dao.model.LiveBqfGift;
import com.kakasure.bqf.dao.model.LiveBqfGiftExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LiveBqfGiftMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunear_live_bqf_gift
     *
     * @mbggenerated Wed Sep 28 16:07:35 CST 2016
     */
    int countByExample(LiveBqfGiftExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunear_live_bqf_gift
     *
     * @mbggenerated Wed Sep 28 16:07:35 CST 2016
     */
    int deleteByExample(LiveBqfGiftExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunear_live_bqf_gift
     *
     * @mbggenerated Wed Sep 28 16:07:35 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunear_live_bqf_gift
     *
     * @mbggenerated Wed Sep 28 16:07:35 CST 2016
     */
    int insertSelective(LiveBqfGift record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunear_live_bqf_gift
     *
     * @mbggenerated Wed Sep 28 16:07:35 CST 2016
     */
    List<LiveBqfGift> selectByExample(LiveBqfGiftExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunear_live_bqf_gift
     *
     * @mbggenerated Wed Sep 28 16:07:35 CST 2016
     */
    LiveBqfGift selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunear_live_bqf_gift
     *
     * @mbggenerated Wed Sep 28 16:07:35 CST 2016
     */
    int updateByExampleSelective(@Param("record") LiveBqfGift record, @Param("example") LiveBqfGiftExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunear_live_bqf_gift
     *
     * @mbggenerated Wed Sep 28 16:07:35 CST 2016
     */
    int updateByExample(@Param("record") LiveBqfGift record, @Param("example") LiveBqfGiftExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunear_live_bqf_gift
     *
     * @mbggenerated Wed Sep 28 16:07:35 CST 2016
     */
    int updateByPrimaryKeySelective(LiveBqfGift record);
}