package com.kakasure.bqf.dao.mapper;

import com.kakasure.bqf.dao.model.LiveBroadcast;
import com.kakasure.bqf.dao.model.LiveBroadcastExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface LiveBroadcastMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunear_live_broadcast
     *
     * @mbggenerated Wed Nov 09 15:01:33 GMT+08:00 2016
     */
    int countByExample(LiveBroadcastExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunear_live_broadcast
     *
     * @mbggenerated Wed Nov 09 15:01:33 GMT+08:00 2016
     */
    int deleteByExample(LiveBroadcastExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunear_live_broadcast
     *
     * @mbggenerated Wed Nov 09 15:01:33 GMT+08:00 2016
     */
    int deleteByPrimaryKey(String liveBroadcastId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunear_live_broadcast
     *
     * @mbggenerated Wed Nov 09 15:01:33 GMT+08:00 2016
     */
    int insertSelective(LiveBroadcast record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunear_live_broadcast
     *
     * @mbggenerated Wed Nov 09 15:01:33 GMT+08:00 2016
     */
    List<LiveBroadcast> selectByExample(LiveBroadcastExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunear_live_broadcast
     *
     * @mbggenerated Wed Nov 09 15:01:33 GMT+08:00 2016
     */
    LiveBroadcast selectByPrimaryKey(String liveBroadcastId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunear_live_broadcast
     *
     * @mbggenerated Wed Nov 09 15:01:33 GMT+08:00 2016
     */
    int updateByExampleSelective(@Param("record") LiveBroadcast record, @Param("example") LiveBroadcastExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunear_live_broadcast
     *
     * @mbggenerated Wed Nov 09 15:01:33 GMT+08:00 2016
     */
    int updateByExample(@Param("record") LiveBroadcast record, @Param("example") LiveBroadcastExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunear_live_broadcast
     *
     * @mbggenerated Wed Nov 09 15:01:33 GMT+08:00 2016
     */
    int updateByPrimaryKeySelective(LiveBroadcast record);
}