package com.kakasure.bqf.dao.mapper;

import com.kakasure.bqf.dao.model.MobileCode;
import com.kakasure.bqf.dao.model.MobileCodeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface MobileCodeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_mobile_code
     *
     * @mbggenerated Tue Sep 27 16:17:16 CST 2016
     */
    int countByExample(MobileCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_mobile_code
     *
     * @mbggenerated Tue Sep 27 16:17:16 CST 2016
     */
    int deleteByExample(MobileCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_mobile_code
     *
     * @mbggenerated Tue Sep 27 16:17:16 CST 2016
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_mobile_code
     *
     * @mbggenerated Tue Sep 27 16:17:16 CST 2016
     */
    int insertSelective(MobileCode record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_mobile_code
     *
     * @mbggenerated Tue Sep 27 16:17:16 CST 2016
     */
    List<MobileCode> selectByExample(MobileCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_mobile_code
     *
     * @mbggenerated Tue Sep 27 16:17:16 CST 2016
     */
    MobileCode selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_mobile_code
     *
     * @mbggenerated Tue Sep 27 16:17:16 CST 2016
     */
    int updateByExampleSelective(@Param("record") MobileCode record, @Param("example") MobileCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_mobile_code
     *
     * @mbggenerated Tue Sep 27 16:17:16 CST 2016
     */
    int updateByExample(@Param("record") MobileCode record, @Param("example") MobileCodeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table common_mobile_code
     *
     * @mbggenerated Tue Sep 27 16:17:16 CST 2016
     */
    int updateByPrimaryKeySelective(MobileCode record);
}