package com.kakasure.bqf.dao.mapper;

import com.kakasure.bqf.dao.model.Order;
import com.kakasure.bqf.dao.model.OrderExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface OrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunear_order
     *
     * @mbggenerated Sat Oct 15 10:03:07 CST 2016
     */
    int countByExample(OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunear_order
     *
     * @mbggenerated Sat Oct 15 10:03:07 CST 2016
     */
    int deleteByExample(OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunear_order
     *
     * @mbggenerated Sat Oct 15 10:03:07 CST 2016
     */
    int deleteByPrimaryKey(String orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunear_order
     *
     * @mbggenerated Sat Oct 15 10:03:07 CST 2016
     */
    int insertSelective(Order record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunear_order
     *
     * @mbggenerated Sat Oct 15 10:03:07 CST 2016
     */
    List<Order> selectByExample(OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunear_order
     *
     * @mbggenerated Sat Oct 15 10:03:07 CST 2016
     */
    Order selectByPrimaryKey(String orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunear_order
     *
     * @mbggenerated Sat Oct 15 10:03:07 CST 2016
     */
    int updateByExampleSelective(@Param("record") Order record, @Param("example") OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunear_order
     *
     * @mbggenerated Sat Oct 15 10:03:07 CST 2016
     */
    int updateByExample(@Param("record") Order record, @Param("example") OrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunear_order
     *
     * @mbggenerated Sat Oct 15 10:03:07 CST 2016
     */
    int updateByPrimaryKeySelective(Order record);
}