package com.kakasure.bqf.dao.mapper;

import com.kakasure.bqf.dao.model.ThemeAnnounce;
import com.kakasure.bqf.dao.model.ThemeAnnounceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ThemeAnnounceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunear_theme_announce
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    int countByExample(ThemeAnnounceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunear_theme_announce
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    int deleteByExample(ThemeAnnounceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunear_theme_announce
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    int insertSelective(ThemeAnnounce record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunear_theme_announce
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    List<ThemeAnnounce> selectByExample(ThemeAnnounceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunear_theme_announce
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    int updateByExampleSelective(@Param("record") ThemeAnnounce record, @Param("example") ThemeAnnounceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunear_theme_announce
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    int updateByExample(@Param("record") ThemeAnnounce record, @Param("example") ThemeAnnounceExample example);
}