package com.kakasure.bqf.dao.mapper;

import com.kakasure.bqf.dao.model.Theme;
import com.kakasure.bqf.dao.model.ThemeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ThemeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunear_theme
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    int countByExample(ThemeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunear_theme
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    int deleteByExample(ThemeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunear_theme
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    int deleteByPrimaryKey(String themeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunear_theme
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    int insertSelective(Theme record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunear_theme
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    List<Theme> selectByExample(ThemeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunear_theme
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    Theme selectByPrimaryKey(String themeId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunear_theme
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    int updateByExampleSelective(@Param("record") Theme record, @Param("example") ThemeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunear_theme
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    int updateByExample(@Param("record") Theme record, @Param("example") ThemeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunear_theme
     *
     * @mbggenerated Thu Sep 22 10:02:32 CST 2016
     */
    int updateByPrimaryKeySelective(Theme record);
}