package com.kakasure.bqf.dao.mapper;

import com.kakasure.bqf.dao.model.Userplus;
import com.kakasure.bqf.dao.model.UserplusExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserplusMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunear_userplus
     *
     * @mbggenerated Tue Nov 29 13:59:55 CST 2016
     */
    int countByExample(UserplusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunear_userplus
     *
     * @mbggenerated Tue Nov 29 13:59:55 CST 2016
     */
    int deleteByExample(UserplusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunear_userplus
     *
     * @mbggenerated Tue Nov 29 13:59:55 CST 2016
     */
    int deleteByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunear_userplus
     *
     * @mbggenerated Tue Nov 29 13:59:55 CST 2016
     */
    int insertSelective(Userplus record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunear_userplus
     *
     * @mbggenerated Tue Nov 29 13:59:55 CST 2016
     */
    List<Userplus> selectByExample(UserplusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunear_userplus
     *
     * @mbggenerated Tue Nov 29 13:59:55 CST 2016
     */
    Userplus selectByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunear_userplus
     *
     * @mbggenerated Tue Nov 29 13:59:55 CST 2016
     */
    int updateByExampleSelective(@Param("record") Userplus record, @Param("example") UserplusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunear_userplus
     *
     * @mbggenerated Tue Nov 29 13:59:55 CST 2016
     */
    int updateByExample(@Param("record") Userplus record, @Param("example") UserplusExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table yunear_userplus
     *
     * @mbggenerated Tue Nov 29 13:59:55 CST 2016
     */
    int updateByPrimaryKeySelective(Userplus record);
}